// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AuthConfigsGetter has a method to return a AuthConfigInterface.
// A group's client should implement this interface.
type AuthConfigsGetter interface {
	AuthConfigs() AuthConfigInterface
}

// AuthConfigInterface has methods to work with AuthConfig resources.
type AuthConfigInterface interface {
	Create(ctx context.Context, authConfig *managementcattleiov3.AuthConfig, opts v1.CreateOptions) (*managementcattleiov3.AuthConfig, error)
	Update(ctx context.Context, authConfig *managementcattleiov3.AuthConfig, opts v1.UpdateOptions) (*managementcattleiov3.AuthConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, authConfig *managementcattleiov3.AuthConfig, opts v1.UpdateOptions) (*managementcattleiov3.AuthConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.AuthConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.AuthConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.AuthConfig, err error)
	AuthConfigExpansion
}

// authConfigs implements AuthConfigInterface
type authConfigs struct {
	*gentype.ClientWithList[*managementcattleiov3.AuthConfig, *managementcattleiov3.AuthConfigList]
}

// newAuthConfigs returns a AuthConfigs
func newAuthConfigs(c *ManagementV3Client) *authConfigs {
	return &authConfigs{
		gentype.NewClientWithList[*managementcattleiov3.AuthConfig, *managementcattleiov3.AuthConfigList](
			"authconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.AuthConfig { return &managementcattleiov3.AuthConfig{} },
			func() *managementcattleiov3.AuthConfigList { return &managementcattleiov3.AuthConfigList{} },
		),
	}
}
