// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AuthProvidersGetter has a method to return a AuthProviderInterface.
// A group's client should implement this interface.
type AuthProvidersGetter interface {
	AuthProviders() AuthProviderInterface
}

// AuthProviderInterface has methods to work with AuthProvider resources.
type AuthProviderInterface interface {
	Create(ctx context.Context, authProvider *managementcattleiov3.AuthProvider, opts v1.CreateOptions) (*managementcattleiov3.AuthProvider, error)
	Update(ctx context.Context, authProvider *managementcattleiov3.AuthProvider, opts v1.UpdateOptions) (*managementcattleiov3.AuthProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.AuthProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.AuthProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.AuthProvider, err error)
	AuthProviderExpansion
}

// authProviders implements AuthProviderInterface
type authProviders struct {
	*gentype.ClientWithList[*managementcattleiov3.AuthProvider, *managementcattleiov3.AuthProviderList]
}

// newAuthProviders returns a AuthProviders
func newAuthProviders(c *ManagementV3Client) *authProviders {
	return &authProviders{
		gentype.NewClientWithList[*managementcattleiov3.AuthProvider, *managementcattleiov3.AuthProviderList](
			"authproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.AuthProvider { return &managementcattleiov3.AuthProvider{} },
			func() *managementcattleiov3.AuthProviderList { return &managementcattleiov3.AuthProviderList{} },
		),
	}
}
