// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CloudCredentialsGetter has a method to return a CloudCredentialInterface.
// A group's client should implement this interface.
type CloudCredentialsGetter interface {
	CloudCredentials(namespace string) CloudCredentialInterface
}

// CloudCredentialInterface has methods to work with CloudCredential resources.
type CloudCredentialInterface interface {
	Create(ctx context.Context, cloudCredential *managementcattleiov3.CloudCredential, opts v1.CreateOptions) (*managementcattleiov3.CloudCredential, error)
	Update(ctx context.Context, cloudCredential *managementcattleiov3.CloudCredential, opts v1.UpdateOptions) (*managementcattleiov3.CloudCredential, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.CloudCredential, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.CloudCredentialList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.CloudCredential, err error)
	CloudCredentialExpansion
}

// cloudCredentials implements CloudCredentialInterface
type cloudCredentials struct {
	*gentype.ClientWithList[*managementcattleiov3.CloudCredential, *managementcattleiov3.CloudCredentialList]
}

// newCloudCredentials returns a CloudCredentials
func newCloudCredentials(c *ManagementV3Client, namespace string) *cloudCredentials {
	return &cloudCredentials{
		gentype.NewClientWithList[*managementcattleiov3.CloudCredential, *managementcattleiov3.CloudCredentialList](
			"cloudcredentials",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *managementcattleiov3.CloudCredential { return &managementcattleiov3.CloudCredential{} },
			func() *managementcattleiov3.CloudCredentialList { return &managementcattleiov3.CloudCredentialList{} },
		),
	}
}
