// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CognitoProvidersGetter has a method to return a CognitoProviderInterface.
// A group's client should implement this interface.
type CognitoProvidersGetter interface {
	CognitoProviders() CognitoProviderInterface
}

// CognitoProviderInterface has methods to work with CognitoProvider resources.
type CognitoProviderInterface interface {
	Create(ctx context.Context, cognitoProvider *managementcattleiov3.CognitoProvider, opts v1.CreateOptions) (*managementcattleiov3.CognitoProvider, error)
	Update(ctx context.Context, cognitoProvider *managementcattleiov3.CognitoProvider, opts v1.UpdateOptions) (*managementcattleiov3.CognitoProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.CognitoProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.CognitoProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.CognitoProvider, err error)
	CognitoProviderExpansion
}

// cognitoProviders implements CognitoProviderInterface
type cognitoProviders struct {
	*gentype.ClientWithList[*managementcattleiov3.CognitoProvider, *managementcattleiov3.CognitoProviderList]
}

// newCognitoProviders returns a CognitoProviders
func newCognitoProviders(c *ManagementV3Client) *cognitoProviders {
	return &cognitoProviders{
		gentype.NewClientWithList[*managementcattleiov3.CognitoProvider, *managementcattleiov3.CognitoProviderList](
			"cognitoproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.CognitoProvider { return &managementcattleiov3.CognitoProvider{} },
			func() *managementcattleiov3.CognitoProviderList { return &managementcattleiov3.CognitoProviderList{} },
		),
	}
}
