// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ComposeConfigsGetter has a method to return a ComposeConfigInterface.
// A group's client should implement this interface.
type ComposeConfigsGetter interface {
	ComposeConfigs() ComposeConfigInterface
}

// ComposeConfigInterface has methods to work with ComposeConfig resources.
type ComposeConfigInterface interface {
	Create(ctx context.Context, composeConfig *managementcattleiov3.ComposeConfig, opts v1.CreateOptions) (*managementcattleiov3.ComposeConfig, error)
	Update(ctx context.Context, composeConfig *managementcattleiov3.ComposeConfig, opts v1.UpdateOptions) (*managementcattleiov3.ComposeConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, composeConfig *managementcattleiov3.ComposeConfig, opts v1.UpdateOptions) (*managementcattleiov3.ComposeConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.ComposeConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.ComposeConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.ComposeConfig, err error)
	ComposeConfigExpansion
}

// composeConfigs implements ComposeConfigInterface
type composeConfigs struct {
	*gentype.ClientWithList[*managementcattleiov3.ComposeConfig, *managementcattleiov3.ComposeConfigList]
}

// newComposeConfigs returns a ComposeConfigs
func newComposeConfigs(c *ManagementV3Client) *composeConfigs {
	return &composeConfigs{
		gentype.NewClientWithList[*managementcattleiov3.ComposeConfig, *managementcattleiov3.ComposeConfigList](
			"composeconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.ComposeConfig { return &managementcattleiov3.ComposeConfig{} },
			func() *managementcattleiov3.ComposeConfigList { return &managementcattleiov3.ComposeConfigList{} },
		),
	}
}
