// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FeaturesGetter has a method to return a FeatureInterface.
// A group's client should implement this interface.
type FeaturesGetter interface {
	Features() FeatureInterface
}

// FeatureInterface has methods to work with Feature resources.
type FeatureInterface interface {
	Create(ctx context.Context, feature *managementcattleiov3.Feature, opts v1.CreateOptions) (*managementcattleiov3.Feature, error)
	Update(ctx context.Context, feature *managementcattleiov3.Feature, opts v1.UpdateOptions) (*managementcattleiov3.Feature, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, feature *managementcattleiov3.Feature, opts v1.UpdateOptions) (*managementcattleiov3.Feature, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.Feature, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.FeatureList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.Feature, err error)
	FeatureExpansion
}

// features implements FeatureInterface
type features struct {
	*gentype.ClientWithList[*managementcattleiov3.Feature, *managementcattleiov3.FeatureList]
}

// newFeatures returns a Features
func newFeatures(c *ManagementV3Client) *features {
	return &features{
		gentype.NewClientWithList[*managementcattleiov3.Feature, *managementcattleiov3.FeatureList](
			"features",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.Feature { return &managementcattleiov3.Feature{} },
			func() *managementcattleiov3.FeatureList { return &managementcattleiov3.FeatureList{} },
		),
	}
}
