// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FleetWorkspacesGetter has a method to return a FleetWorkspaceInterface.
// A group's client should implement this interface.
type FleetWorkspacesGetter interface {
	FleetWorkspaces() FleetWorkspaceInterface
}

// FleetWorkspaceInterface has methods to work with FleetWorkspace resources.
type FleetWorkspaceInterface interface {
	Create(ctx context.Context, fleetWorkspace *managementcattleiov3.FleetWorkspace, opts v1.CreateOptions) (*managementcattleiov3.FleetWorkspace, error)
	Update(ctx context.Context, fleetWorkspace *managementcattleiov3.FleetWorkspace, opts v1.UpdateOptions) (*managementcattleiov3.FleetWorkspace, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, fleetWorkspace *managementcattleiov3.FleetWorkspace, opts v1.UpdateOptions) (*managementcattleiov3.FleetWorkspace, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.FleetWorkspace, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.FleetWorkspaceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.FleetWorkspace, err error)
	FleetWorkspaceExpansion
}

// fleetWorkspaces implements FleetWorkspaceInterface
type fleetWorkspaces struct {
	*gentype.ClientWithList[*managementcattleiov3.FleetWorkspace, *managementcattleiov3.FleetWorkspaceList]
}

// newFleetWorkspaces returns a FleetWorkspaces
func newFleetWorkspaces(c *ManagementV3Client) *fleetWorkspaces {
	return &fleetWorkspaces{
		gentype.NewClientWithList[*managementcattleiov3.FleetWorkspace, *managementcattleiov3.FleetWorkspaceList](
			"fleetworkspaces",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.FleetWorkspace { return &managementcattleiov3.FleetWorkspace{} },
			func() *managementcattleiov3.FleetWorkspaceList { return &managementcattleiov3.FleetWorkspaceList{} },
		),
	}
}
