// Code generated by client-gen. DO NOT EDIT.

package v3

type APIServiceExpansion interface{}

type ActiveDirectoryProviderExpansion interface{}

type AuthConfigExpansion interface{}

type AuthProviderExpansion interface{}

type AuthTokenExpansion interface{}

type AzureADProviderExpansion interface{}

type CloudCredentialExpansion interface{}

type ClusterExpansion interface{}

type ClusterProxyConfigExpansion interface{}

type ClusterRegistrationTokenExpansion interface{}

type ClusterRoleTemplateBindingExpansion interface{}

type CognitoProviderExpansion interface{}

type ComposeConfigExpansion interface{}

type DynamicSchemaExpansion interface{}

type FeatureExpansion interface{}

type FleetWorkspaceExpansion interface{}

type FreeIpaProviderExpansion interface{}

type GenericOIDCProviderExpansion interface{}

type GithubAppConfigExpansion interface{}

type GithubAppProviderExpansion interface{}

type GithubConfigExpansion interface{}

type GithubProviderExpansion interface{}

type GlobalRoleExpansion interface{}

type GlobalRoleBindingExpansion interface{}

type GoogleOAuthProviderExpansion interface{}

type GroupExpansion interface{}

type GroupMemberExpansion interface{}

type KeyCloakOIDCProviderExpansion interface{}

type KontainerDriverExpansion interface{}

type LocalProviderExpansion interface{}

type ManagedChartExpansion interface{}

type NodeExpansion interface{}

type NodeDriverExpansion interface{}

type OIDCClientExpansion interface{}

type OIDCProviderExpansion interface{}

type OpenLdapProviderExpansion interface{}

type PodSecurityAdmissionConfigurationTemplateExpansion interface{}

type PreferenceExpansion interface{}

type PrincipalExpansion interface{}

type ProjectExpansion interface{}

type ProjectNetworkPolicyExpansion interface{}

type ProjectRoleTemplateBindingExpansion interface{}

type ProxyEndpointExpansion interface{}

type RancherUserNotificationExpansion interface{}

type RoleTemplateExpansion interface{}

type SamlProviderExpansion interface{}

type SamlTokenExpansion interface{}

type SettingExpansion interface{}

type TokenExpansion interface{}

type UserExpansion interface{}

type UserAttributeExpansion interface{}
