// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GenericOIDCProvidersGetter has a method to return a GenericOIDCProviderInterface.
// A group's client should implement this interface.
type GenericOIDCProvidersGetter interface {
	GenericOIDCProviders() GenericOIDCProviderInterface
}

// GenericOIDCProviderInterface has methods to work with GenericOIDCProvider resources.
type GenericOIDCProviderInterface interface {
	Create(ctx context.Context, genericOIDCProvider *managementcattleiov3.GenericOIDCProvider, opts v1.CreateOptions) (*managementcattleiov3.GenericOIDCProvider, error)
	Update(ctx context.Context, genericOIDCProvider *managementcattleiov3.GenericOIDCProvider, opts v1.UpdateOptions) (*managementcattleiov3.GenericOIDCProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.GenericOIDCProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.GenericOIDCProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.GenericOIDCProvider, err error)
	GenericOIDCProviderExpansion
}

// genericOIDCProviders implements GenericOIDCProviderInterface
type genericOIDCProviders struct {
	*gentype.ClientWithList[*managementcattleiov3.GenericOIDCProvider, *managementcattleiov3.GenericOIDCProviderList]
}

// newGenericOIDCProviders returns a GenericOIDCProviders
func newGenericOIDCProviders(c *ManagementV3Client) *genericOIDCProviders {
	return &genericOIDCProviders{
		gentype.NewClientWithList[*managementcattleiov3.GenericOIDCProvider, *managementcattleiov3.GenericOIDCProviderList](
			"genericoidcproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.GenericOIDCProvider { return &managementcattleiov3.GenericOIDCProvider{} },
			func() *managementcattleiov3.GenericOIDCProviderList {
				return &managementcattleiov3.GenericOIDCProviderList{}
			},
		),
	}
}
