// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GithubAppConfigsGetter has a method to return a GithubAppConfigInterface.
// A group's client should implement this interface.
type GithubAppConfigsGetter interface {
	GithubAppConfigs() GithubAppConfigInterface
}

// GithubAppConfigInterface has methods to work with GithubAppConfig resources.
type GithubAppConfigInterface interface {
	Create(ctx context.Context, githubAppConfig *managementcattleiov3.GithubAppConfig, opts v1.CreateOptions) (*managementcattleiov3.GithubAppConfig, error)
	Update(ctx context.Context, githubAppConfig *managementcattleiov3.GithubAppConfig, opts v1.UpdateOptions) (*managementcattleiov3.GithubAppConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.GithubAppConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.GithubAppConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.GithubAppConfig, err error)
	GithubAppConfigExpansion
}

// githubAppConfigs implements GithubAppConfigInterface
type githubAppConfigs struct {
	*gentype.ClientWithList[*managementcattleiov3.GithubAppConfig, *managementcattleiov3.GithubAppConfigList]
}

// newGithubAppConfigs returns a GithubAppConfigs
func newGithubAppConfigs(c *ManagementV3Client) *githubAppConfigs {
	return &githubAppConfigs{
		gentype.NewClientWithList[*managementcattleiov3.GithubAppConfig, *managementcattleiov3.GithubAppConfigList](
			"githubappconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.GithubAppConfig { return &managementcattleiov3.GithubAppConfig{} },
			func() *managementcattleiov3.GithubAppConfigList { return &managementcattleiov3.GithubAppConfigList{} },
		),
	}
}
