// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GithubAppProvidersGetter has a method to return a GithubAppProviderInterface.
// A group's client should implement this interface.
type GithubAppProvidersGetter interface {
	GithubAppProviders() GithubAppProviderInterface
}

// GithubAppProviderInterface has methods to work with GithubAppProvider resources.
type GithubAppProviderInterface interface {
	Create(ctx context.Context, githubAppProvider *managementcattleiov3.GithubAppProvider, opts v1.CreateOptions) (*managementcattleiov3.GithubAppProvider, error)
	Update(ctx context.Context, githubAppProvider *managementcattleiov3.GithubAppProvider, opts v1.UpdateOptions) (*managementcattleiov3.GithubAppProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.GithubAppProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.GithubAppProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.GithubAppProvider, err error)
	GithubAppProviderExpansion
}

// githubAppProviders implements GithubAppProviderInterface
type githubAppProviders struct {
	*gentype.ClientWithList[*managementcattleiov3.GithubAppProvider, *managementcattleiov3.GithubAppProviderList]
}

// newGithubAppProviders returns a GithubAppProviders
func newGithubAppProviders(c *ManagementV3Client) *githubAppProviders {
	return &githubAppProviders{
		gentype.NewClientWithList[*managementcattleiov3.GithubAppProvider, *managementcattleiov3.GithubAppProviderList](
			"githubappproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.GithubAppProvider { return &managementcattleiov3.GithubAppProvider{} },
			func() *managementcattleiov3.GithubAppProviderList {
				return &managementcattleiov3.GithubAppProviderList{}
			},
		),
	}
}
