// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GithubConfigsGetter has a method to return a GithubConfigInterface.
// A group's client should implement this interface.
type GithubConfigsGetter interface {
	GithubConfigs() GithubConfigInterface
}

// GithubConfigInterface has methods to work with GithubConfig resources.
type GithubConfigInterface interface {
	Create(ctx context.Context, githubConfig *managementcattleiov3.GithubConfig, opts v1.CreateOptions) (*managementcattleiov3.GithubConfig, error)
	Update(ctx context.Context, githubConfig *managementcattleiov3.GithubConfig, opts v1.UpdateOptions) (*managementcattleiov3.GithubConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.GithubConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.GithubConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.GithubConfig, err error)
	GithubConfigExpansion
}

// githubConfigs implements GithubConfigInterface
type githubConfigs struct {
	*gentype.ClientWithList[*managementcattleiov3.GithubConfig, *managementcattleiov3.GithubConfigList]
}

// newGithubConfigs returns a GithubConfigs
func newGithubConfigs(c *ManagementV3Client) *githubConfigs {
	return &githubConfigs{
		gentype.NewClientWithList[*managementcattleiov3.GithubConfig, *managementcattleiov3.GithubConfigList](
			"githubconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.GithubConfig { return &managementcattleiov3.GithubConfig{} },
			func() *managementcattleiov3.GithubConfigList { return &managementcattleiov3.GithubConfigList{} },
		),
	}
}
