// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GlobalRolesGetter has a method to return a GlobalRoleInterface.
// A group's client should implement this interface.
type GlobalRolesGetter interface {
	GlobalRoles() GlobalRoleInterface
}

// GlobalRoleInterface has methods to work with GlobalRole resources.
type GlobalRoleInterface interface {
	Create(ctx context.Context, globalRole *managementcattleiov3.GlobalRole, opts v1.CreateOptions) (*managementcattleiov3.GlobalRole, error)
	Update(ctx context.Context, globalRole *managementcattleiov3.GlobalRole, opts v1.UpdateOptions) (*managementcattleiov3.GlobalRole, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, globalRole *managementcattleiov3.GlobalRole, opts v1.UpdateOptions) (*managementcattleiov3.GlobalRole, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.GlobalRole, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.GlobalRoleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.GlobalRole, err error)
	GlobalRoleExpansion
}

// globalRoles implements GlobalRoleInterface
type globalRoles struct {
	*gentype.ClientWithList[*managementcattleiov3.GlobalRole, *managementcattleiov3.GlobalRoleList]
}

// newGlobalRoles returns a GlobalRoles
func newGlobalRoles(c *ManagementV3Client) *globalRoles {
	return &globalRoles{
		gentype.NewClientWithList[*managementcattleiov3.GlobalRole, *managementcattleiov3.GlobalRoleList](
			"globalroles",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.GlobalRole { return &managementcattleiov3.GlobalRole{} },
			func() *managementcattleiov3.GlobalRoleList { return &managementcattleiov3.GlobalRoleList{} },
		),
	}
}
