// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GoogleOAuthProvidersGetter has a method to return a GoogleOAuthProviderInterface.
// A group's client should implement this interface.
type GoogleOAuthProvidersGetter interface {
	GoogleOAuthProviders() GoogleOAuthProviderInterface
}

// GoogleOAuthProviderInterface has methods to work with GoogleOAuthProvider resources.
type GoogleOAuthProviderInterface interface {
	Create(ctx context.Context, googleOAuthProvider *managementcattleiov3.GoogleOAuthProvider, opts v1.CreateOptions) (*managementcattleiov3.GoogleOAuthProvider, error)
	Update(ctx context.Context, googleOAuthProvider *managementcattleiov3.GoogleOAuthProvider, opts v1.UpdateOptions) (*managementcattleiov3.GoogleOAuthProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.GoogleOAuthProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.GoogleOAuthProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.GoogleOAuthProvider, err error)
	GoogleOAuthProviderExpansion
}

// googleOAuthProviders implements GoogleOAuthProviderInterface
type googleOAuthProviders struct {
	*gentype.ClientWithList[*managementcattleiov3.GoogleOAuthProvider, *managementcattleiov3.GoogleOAuthProviderList]
}

// newGoogleOAuthProviders returns a GoogleOAuthProviders
func newGoogleOAuthProviders(c *ManagementV3Client) *googleOAuthProviders {
	return &googleOAuthProviders{
		gentype.NewClientWithList[*managementcattleiov3.GoogleOAuthProvider, *managementcattleiov3.GoogleOAuthProviderList](
			"googleoauthproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.GoogleOAuthProvider { return &managementcattleiov3.GoogleOAuthProvider{} },
			func() *managementcattleiov3.GoogleOAuthProviderList {
				return &managementcattleiov3.GoogleOAuthProviderList{}
			},
		),
	}
}
