// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GroupsGetter has a method to return a GroupInterface.
// A group's client should implement this interface.
type GroupsGetter interface {
	Groups() GroupInterface
}

// GroupInterface has methods to work with Group resources.
type GroupInterface interface {
	Create(ctx context.Context, group *managementcattleiov3.Group, opts v1.CreateOptions) (*managementcattleiov3.Group, error)
	Update(ctx context.Context, group *managementcattleiov3.Group, opts v1.UpdateOptions) (*managementcattleiov3.Group, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.Group, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.GroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.Group, err error)
	GroupExpansion
}

// groups implements GroupInterface
type groups struct {
	*gentype.ClientWithList[*managementcattleiov3.Group, *managementcattleiov3.GroupList]
}

// newGroups returns a Groups
func newGroups(c *ManagementV3Client) *groups {
	return &groups{
		gentype.NewClientWithList[*managementcattleiov3.Group, *managementcattleiov3.GroupList](
			"groups",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.Group { return &managementcattleiov3.Group{} },
			func() *managementcattleiov3.GroupList { return &managementcattleiov3.GroupList{} },
		),
	}
}
