// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KeyCloakOIDCProvidersGetter has a method to return a KeyCloakOIDCProviderInterface.
// A group's client should implement this interface.
type KeyCloakOIDCProvidersGetter interface {
	KeyCloakOIDCProviders() KeyCloakOIDCProviderInterface
}

// KeyCloakOIDCProviderInterface has methods to work with KeyCloakOIDCProvider resources.
type KeyCloakOIDCProviderInterface interface {
	Create(ctx context.Context, keyCloakOIDCProvider *managementcattleiov3.KeyCloakOIDCProvider, opts v1.CreateOptions) (*managementcattleiov3.KeyCloakOIDCProvider, error)
	Update(ctx context.Context, keyCloakOIDCProvider *managementcattleiov3.KeyCloakOIDCProvider, opts v1.UpdateOptions) (*managementcattleiov3.KeyCloakOIDCProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.KeyCloakOIDCProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.KeyCloakOIDCProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.KeyCloakOIDCProvider, err error)
	KeyCloakOIDCProviderExpansion
}

// keyCloakOIDCProviders implements KeyCloakOIDCProviderInterface
type keyCloakOIDCProviders struct {
	*gentype.ClientWithList[*managementcattleiov3.KeyCloakOIDCProvider, *managementcattleiov3.KeyCloakOIDCProviderList]
}

// newKeyCloakOIDCProviders returns a KeyCloakOIDCProviders
func newKeyCloakOIDCProviders(c *ManagementV3Client) *keyCloakOIDCProviders {
	return &keyCloakOIDCProviders{
		gentype.NewClientWithList[*managementcattleiov3.KeyCloakOIDCProvider, *managementcattleiov3.KeyCloakOIDCProviderList](
			"keycloakoidcproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.KeyCloakOIDCProvider { return &managementcattleiov3.KeyCloakOIDCProvider{} },
			func() *managementcattleiov3.KeyCloakOIDCProviderList {
				return &managementcattleiov3.KeyCloakOIDCProviderList{}
			},
		),
	}
}
