// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// KontainerDriversGetter has a method to return a KontainerDriverInterface.
// A group's client should implement this interface.
type KontainerDriversGetter interface {
	KontainerDrivers() KontainerDriverInterface
}

// KontainerDriverInterface has methods to work with KontainerDriver resources.
type KontainerDriverInterface interface {
	Create(ctx context.Context, kontainerDriver *managementcattleiov3.KontainerDriver, opts v1.CreateOptions) (*managementcattleiov3.KontainerDriver, error)
	Update(ctx context.Context, kontainerDriver *managementcattleiov3.KontainerDriver, opts v1.UpdateOptions) (*managementcattleiov3.KontainerDriver, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, kontainerDriver *managementcattleiov3.KontainerDriver, opts v1.UpdateOptions) (*managementcattleiov3.KontainerDriver, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.KontainerDriver, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.KontainerDriverList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.KontainerDriver, err error)
	KontainerDriverExpansion
}

// kontainerDrivers implements KontainerDriverInterface
type kontainerDrivers struct {
	*gentype.ClientWithList[*managementcattleiov3.KontainerDriver, *managementcattleiov3.KontainerDriverList]
}

// newKontainerDrivers returns a KontainerDrivers
func newKontainerDrivers(c *ManagementV3Client) *kontainerDrivers {
	return &kontainerDrivers{
		gentype.NewClientWithList[*managementcattleiov3.KontainerDriver, *managementcattleiov3.KontainerDriverList](
			"kontainerdrivers",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.KontainerDriver { return &managementcattleiov3.KontainerDriver{} },
			func() *managementcattleiov3.KontainerDriverList { return &managementcattleiov3.KontainerDriverList{} },
		),
	}
}
