// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LocalProvidersGetter has a method to return a LocalProviderInterface.
// A group's client should implement this interface.
type LocalProvidersGetter interface {
	LocalProviders() LocalProviderInterface
}

// LocalProviderInterface has methods to work with LocalProvider resources.
type LocalProviderInterface interface {
	Create(ctx context.Context, localProvider *managementcattleiov3.LocalProvider, opts v1.CreateOptions) (*managementcattleiov3.LocalProvider, error)
	Update(ctx context.Context, localProvider *managementcattleiov3.LocalProvider, opts v1.UpdateOptions) (*managementcattleiov3.LocalProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.LocalProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.LocalProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.LocalProvider, err error)
	LocalProviderExpansion
}

// localProviders implements LocalProviderInterface
type localProviders struct {
	*gentype.ClientWithList[*managementcattleiov3.LocalProvider, *managementcattleiov3.LocalProviderList]
}

// newLocalProviders returns a LocalProviders
func newLocalProviders(c *ManagementV3Client) *localProviders {
	return &localProviders{
		gentype.NewClientWithList[*managementcattleiov3.LocalProvider, *managementcattleiov3.LocalProviderList](
			"localproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.LocalProvider { return &managementcattleiov3.LocalProvider{} },
			func() *managementcattleiov3.LocalProviderList { return &managementcattleiov3.LocalProviderList{} },
		),
	}
}
