// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	http "net/http"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type ManagementV3Interface interface {
	RESTClient() rest.Interface
	APIServicesGetter
	ActiveDirectoryProvidersGetter
	AuthConfigsGetter
	AuthProvidersGetter
	AuthTokensGetter
	AzureADProvidersGetter
	CloudCredentialsGetter
	ClustersGetter
	ClusterProxyConfigsGetter
	ClusterRegistrationTokensGetter
	ClusterRoleTemplateBindingsGetter
	CognitoProvidersGetter
	ComposeConfigsGetter
	DynamicSchemasGetter
	FeaturesGetter
	FleetWorkspacesGetter
	FreeIpaProvidersGetter
	GenericOIDCProvidersGetter
	GithubAppConfigsGetter
	GithubAppProvidersGetter
	GithubConfigsGetter
	GithubProvidersGetter
	GlobalRolesGetter
	GlobalRoleBindingsGetter
	GoogleOAuthProvidersGetter
	GroupsGetter
	GroupMembersGetter
	KeyCloakOIDCProvidersGetter
	KontainerDriversGetter
	LocalProvidersGetter
	ManagedChartsGetter
	NodesGetter
	NodeDriversGetter
	OIDCClientsGetter
	OIDCProvidersGetter
	OpenLdapProvidersGetter
	PodSecurityAdmissionConfigurationTemplatesGetter
	PreferencesGetter
	PrincipalsGetter
	ProjectsGetter
	ProjectNetworkPoliciesGetter
	ProjectRoleTemplateBindingsGetter
	ProxyEndpointsGetter
	RancherUserNotificationsGetter
	RoleTemplatesGetter
	SamlProvidersGetter
	SamlTokensGetter
	SettingsGetter
	TokensGetter
	UsersGetter
	UserAttributesGetter
}

// ManagementV3Client is used to interact with features provided by the management.cattle.io group.
type ManagementV3Client struct {
	restClient rest.Interface
}

func (c *ManagementV3Client) APIServices() APIServiceInterface {
	return newAPIServices(c)
}

func (c *ManagementV3Client) ActiveDirectoryProviders() ActiveDirectoryProviderInterface {
	return newActiveDirectoryProviders(c)
}

func (c *ManagementV3Client) AuthConfigs() AuthConfigInterface {
	return newAuthConfigs(c)
}

func (c *ManagementV3Client) AuthProviders() AuthProviderInterface {
	return newAuthProviders(c)
}

func (c *ManagementV3Client) AuthTokens() AuthTokenInterface {
	return newAuthTokens(c)
}

func (c *ManagementV3Client) AzureADProviders() AzureADProviderInterface {
	return newAzureADProviders(c)
}

func (c *ManagementV3Client) CloudCredentials(namespace string) CloudCredentialInterface {
	return newCloudCredentials(c, namespace)
}

func (c *ManagementV3Client) Clusters() ClusterInterface {
	return newClusters(c)
}

func (c *ManagementV3Client) ClusterProxyConfigs(namespace string) ClusterProxyConfigInterface {
	return newClusterProxyConfigs(c, namespace)
}

func (c *ManagementV3Client) ClusterRegistrationTokens(namespace string) ClusterRegistrationTokenInterface {
	return newClusterRegistrationTokens(c, namespace)
}

func (c *ManagementV3Client) ClusterRoleTemplateBindings(namespace string) ClusterRoleTemplateBindingInterface {
	return newClusterRoleTemplateBindings(c, namespace)
}

func (c *ManagementV3Client) CognitoProviders() CognitoProviderInterface {
	return newCognitoProviders(c)
}

func (c *ManagementV3Client) ComposeConfigs() ComposeConfigInterface {
	return newComposeConfigs(c)
}

func (c *ManagementV3Client) DynamicSchemas() DynamicSchemaInterface {
	return newDynamicSchemas(c)
}

func (c *ManagementV3Client) Features() FeatureInterface {
	return newFeatures(c)
}

func (c *ManagementV3Client) FleetWorkspaces() FleetWorkspaceInterface {
	return newFleetWorkspaces(c)
}

func (c *ManagementV3Client) FreeIpaProviders() FreeIpaProviderInterface {
	return newFreeIpaProviders(c)
}

func (c *ManagementV3Client) GenericOIDCProviders() GenericOIDCProviderInterface {
	return newGenericOIDCProviders(c)
}

func (c *ManagementV3Client) GithubAppConfigs() GithubAppConfigInterface {
	return newGithubAppConfigs(c)
}

func (c *ManagementV3Client) GithubAppProviders() GithubAppProviderInterface {
	return newGithubAppProviders(c)
}

func (c *ManagementV3Client) GithubConfigs() GithubConfigInterface {
	return newGithubConfigs(c)
}

func (c *ManagementV3Client) GithubProviders() GithubProviderInterface {
	return newGithubProviders(c)
}

func (c *ManagementV3Client) GlobalRoles() GlobalRoleInterface {
	return newGlobalRoles(c)
}

func (c *ManagementV3Client) GlobalRoleBindings() GlobalRoleBindingInterface {
	return newGlobalRoleBindings(c)
}

func (c *ManagementV3Client) GoogleOAuthProviders() GoogleOAuthProviderInterface {
	return newGoogleOAuthProviders(c)
}

func (c *ManagementV3Client) Groups() GroupInterface {
	return newGroups(c)
}

func (c *ManagementV3Client) GroupMembers() GroupMemberInterface {
	return newGroupMembers(c)
}

func (c *ManagementV3Client) KeyCloakOIDCProviders() KeyCloakOIDCProviderInterface {
	return newKeyCloakOIDCProviders(c)
}

func (c *ManagementV3Client) KontainerDrivers() KontainerDriverInterface {
	return newKontainerDrivers(c)
}

func (c *ManagementV3Client) LocalProviders() LocalProviderInterface {
	return newLocalProviders(c)
}

func (c *ManagementV3Client) ManagedCharts(namespace string) ManagedChartInterface {
	return newManagedCharts(c, namespace)
}

func (c *ManagementV3Client) Nodes(namespace string) NodeInterface {
	return newNodes(c, namespace)
}

func (c *ManagementV3Client) NodeDrivers() NodeDriverInterface {
	return newNodeDrivers(c)
}

func (c *ManagementV3Client) OIDCClients() OIDCClientInterface {
	return newOIDCClients(c)
}

func (c *ManagementV3Client) OIDCProviders() OIDCProviderInterface {
	return newOIDCProviders(c)
}

func (c *ManagementV3Client) OpenLdapProviders() OpenLdapProviderInterface {
	return newOpenLdapProviders(c)
}

func (c *ManagementV3Client) PodSecurityAdmissionConfigurationTemplates() PodSecurityAdmissionConfigurationTemplateInterface {
	return newPodSecurityAdmissionConfigurationTemplates(c)
}

func (c *ManagementV3Client) Preferences(namespace string) PreferenceInterface {
	return newPreferences(c, namespace)
}

func (c *ManagementV3Client) Principals() PrincipalInterface {
	return newPrincipals(c)
}

func (c *ManagementV3Client) Projects(namespace string) ProjectInterface {
	return newProjects(c, namespace)
}

func (c *ManagementV3Client) ProjectNetworkPolicies(namespace string) ProjectNetworkPolicyInterface {
	return newProjectNetworkPolicies(c, namespace)
}

func (c *ManagementV3Client) ProjectRoleTemplateBindings(namespace string) ProjectRoleTemplateBindingInterface {
	return newProjectRoleTemplateBindings(c, namespace)
}

func (c *ManagementV3Client) ProxyEndpoints() ProxyEndpointInterface {
	return newProxyEndpoints(c)
}

func (c *ManagementV3Client) RancherUserNotifications() RancherUserNotificationInterface {
	return newRancherUserNotifications(c)
}

func (c *ManagementV3Client) RoleTemplates() RoleTemplateInterface {
	return newRoleTemplates(c)
}

func (c *ManagementV3Client) SamlProviders() SamlProviderInterface {
	return newSamlProviders(c)
}

func (c *ManagementV3Client) SamlTokens(namespace string) SamlTokenInterface {
	return newSamlTokens(c, namespace)
}

func (c *ManagementV3Client) Settings() SettingInterface {
	return newSettings(c)
}

func (c *ManagementV3Client) Tokens() TokenInterface {
	return newTokens(c)
}

func (c *ManagementV3Client) Users() UserInterface {
	return newUsers(c)
}

func (c *ManagementV3Client) UserAttributes() UserAttributeInterface {
	return newUserAttributes(c)
}

// NewForConfig creates a new ManagementV3Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*ManagementV3Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new ManagementV3Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*ManagementV3Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &ManagementV3Client{client}, nil
}

// NewForConfigOrDie creates a new ManagementV3Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ManagementV3Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ManagementV3Client for the given RESTClient.
func New(c rest.Interface) *ManagementV3Client {
	return &ManagementV3Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := managementcattleiov3.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ManagementV3Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
