// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NodesGetter has a method to return a NodeInterface.
// A group's client should implement this interface.
type NodesGetter interface {
	Nodes(namespace string) NodeInterface
}

// NodeInterface has methods to work with Node resources.
type NodeInterface interface {
	Create(ctx context.Context, node *managementcattleiov3.Node, opts v1.CreateOptions) (*managementcattleiov3.Node, error)
	Update(ctx context.Context, node *managementcattleiov3.Node, opts v1.UpdateOptions) (*managementcattleiov3.Node, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, node *managementcattleiov3.Node, opts v1.UpdateOptions) (*managementcattleiov3.Node, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.Node, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.NodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.Node, err error)
	NodeExpansion
}

// nodes implements NodeInterface
type nodes struct {
	*gentype.ClientWithList[*managementcattleiov3.Node, *managementcattleiov3.NodeList]
}

// newNodes returns a Nodes
func newNodes(c *ManagementV3Client, namespace string) *nodes {
	return &nodes{
		gentype.NewClientWithList[*managementcattleiov3.Node, *managementcattleiov3.NodeList](
			"nodes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *managementcattleiov3.Node { return &managementcattleiov3.Node{} },
			func() *managementcattleiov3.NodeList { return &managementcattleiov3.NodeList{} },
		),
	}
}
