// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OIDCClientsGetter has a method to return a OIDCClientInterface.
// A group's client should implement this interface.
type OIDCClientsGetter interface {
	OIDCClients() OIDCClientInterface
}

// OIDCClientInterface has methods to work with OIDCClient resources.
type OIDCClientInterface interface {
	Create(ctx context.Context, oIDCClient *managementcattleiov3.OIDCClient, opts v1.CreateOptions) (*managementcattleiov3.OIDCClient, error)
	Update(ctx context.Context, oIDCClient *managementcattleiov3.OIDCClient, opts v1.UpdateOptions) (*managementcattleiov3.OIDCClient, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, oIDCClient *managementcattleiov3.OIDCClient, opts v1.UpdateOptions) (*managementcattleiov3.OIDCClient, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.OIDCClient, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.OIDCClientList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.OIDCClient, err error)
	OIDCClientExpansion
}

// oIDCClients implements OIDCClientInterface
type oIDCClients struct {
	*gentype.ClientWithList[*managementcattleiov3.OIDCClient, *managementcattleiov3.OIDCClientList]
}

// newOIDCClients returns a OIDCClients
func newOIDCClients(c *ManagementV3Client) *oIDCClients {
	return &oIDCClients{
		gentype.NewClientWithList[*managementcattleiov3.OIDCClient, *managementcattleiov3.OIDCClientList](
			"oidcclients",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.OIDCClient { return &managementcattleiov3.OIDCClient{} },
			func() *managementcattleiov3.OIDCClientList { return &managementcattleiov3.OIDCClientList{} },
		),
	}
}
