// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OIDCProvidersGetter has a method to return a OIDCProviderInterface.
// A group's client should implement this interface.
type OIDCProvidersGetter interface {
	OIDCProviders() OIDCProviderInterface
}

// OIDCProviderInterface has methods to work with OIDCProvider resources.
type OIDCProviderInterface interface {
	Create(ctx context.Context, oIDCProvider *managementcattleiov3.OIDCProvider, opts v1.CreateOptions) (*managementcattleiov3.OIDCProvider, error)
	Update(ctx context.Context, oIDCProvider *managementcattleiov3.OIDCProvider, opts v1.UpdateOptions) (*managementcattleiov3.OIDCProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.OIDCProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.OIDCProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.OIDCProvider, err error)
	OIDCProviderExpansion
}

// oIDCProviders implements OIDCProviderInterface
type oIDCProviders struct {
	*gentype.ClientWithList[*managementcattleiov3.OIDCProvider, *managementcattleiov3.OIDCProviderList]
}

// newOIDCProviders returns a OIDCProviders
func newOIDCProviders(c *ManagementV3Client) *oIDCProviders {
	return &oIDCProviders{
		gentype.NewClientWithList[*managementcattleiov3.OIDCProvider, *managementcattleiov3.OIDCProviderList](
			"oidcproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.OIDCProvider { return &managementcattleiov3.OIDCProvider{} },
			func() *managementcattleiov3.OIDCProviderList { return &managementcattleiov3.OIDCProviderList{} },
		),
	}
}
