// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PreferencesGetter has a method to return a PreferenceInterface.
// A group's client should implement this interface.
type PreferencesGetter interface {
	Preferences(namespace string) PreferenceInterface
}

// PreferenceInterface has methods to work with Preference resources.
type PreferenceInterface interface {
	Create(ctx context.Context, preference *managementcattleiov3.Preference, opts v1.CreateOptions) (*managementcattleiov3.Preference, error)
	Update(ctx context.Context, preference *managementcattleiov3.Preference, opts v1.UpdateOptions) (*managementcattleiov3.Preference, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.Preference, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.PreferenceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.Preference, err error)
	PreferenceExpansion
}

// preferences implements PreferenceInterface
type preferences struct {
	*gentype.ClientWithList[*managementcattleiov3.Preference, *managementcattleiov3.PreferenceList]
}

// newPreferences returns a Preferences
func newPreferences(c *ManagementV3Client, namespace string) *preferences {
	return &preferences{
		gentype.NewClientWithList[*managementcattleiov3.Preference, *managementcattleiov3.PreferenceList](
			"preferences",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *managementcattleiov3.Preference { return &managementcattleiov3.Preference{} },
			func() *managementcattleiov3.PreferenceList { return &managementcattleiov3.PreferenceList{} },
		),
	}
}
