// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PrincipalsGetter has a method to return a PrincipalInterface.
// A group's client should implement this interface.
type PrincipalsGetter interface {
	Principals() PrincipalInterface
}

// PrincipalInterface has methods to work with Principal resources.
type PrincipalInterface interface {
	Create(ctx context.Context, principal *managementcattleiov3.Principal, opts v1.CreateOptions) (*managementcattleiov3.Principal, error)
	Update(ctx context.Context, principal *managementcattleiov3.Principal, opts v1.UpdateOptions) (*managementcattleiov3.Principal, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.Principal, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.PrincipalList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.Principal, err error)
	PrincipalExpansion
}

// principals implements PrincipalInterface
type principals struct {
	*gentype.ClientWithList[*managementcattleiov3.Principal, *managementcattleiov3.PrincipalList]
}

// newPrincipals returns a Principals
func newPrincipals(c *ManagementV3Client) *principals {
	return &principals{
		gentype.NewClientWithList[*managementcattleiov3.Principal, *managementcattleiov3.PrincipalList](
			"principals",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.Principal { return &managementcattleiov3.Principal{} },
			func() *managementcattleiov3.PrincipalList { return &managementcattleiov3.PrincipalList{} },
		),
	}
}
