// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ProjectNetworkPoliciesGetter has a method to return a ProjectNetworkPolicyInterface.
// A group's client should implement this interface.
type ProjectNetworkPoliciesGetter interface {
	ProjectNetworkPolicies(namespace string) ProjectNetworkPolicyInterface
}

// ProjectNetworkPolicyInterface has methods to work with ProjectNetworkPolicy resources.
type ProjectNetworkPolicyInterface interface {
	Create(ctx context.Context, projectNetworkPolicy *managementcattleiov3.ProjectNetworkPolicy, opts v1.CreateOptions) (*managementcattleiov3.ProjectNetworkPolicy, error)
	Update(ctx context.Context, projectNetworkPolicy *managementcattleiov3.ProjectNetworkPolicy, opts v1.UpdateOptions) (*managementcattleiov3.ProjectNetworkPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, projectNetworkPolicy *managementcattleiov3.ProjectNetworkPolicy, opts v1.UpdateOptions) (*managementcattleiov3.ProjectNetworkPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.ProjectNetworkPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.ProjectNetworkPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.ProjectNetworkPolicy, err error)
	ProjectNetworkPolicyExpansion
}

// projectNetworkPolicies implements ProjectNetworkPolicyInterface
type projectNetworkPolicies struct {
	*gentype.ClientWithList[*managementcattleiov3.ProjectNetworkPolicy, *managementcattleiov3.ProjectNetworkPolicyList]
}

// newProjectNetworkPolicies returns a ProjectNetworkPolicies
func newProjectNetworkPolicies(c *ManagementV3Client, namespace string) *projectNetworkPolicies {
	return &projectNetworkPolicies{
		gentype.NewClientWithList[*managementcattleiov3.ProjectNetworkPolicy, *managementcattleiov3.ProjectNetworkPolicyList](
			"projectnetworkpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *managementcattleiov3.ProjectNetworkPolicy { return &managementcattleiov3.ProjectNetworkPolicy{} },
			func() *managementcattleiov3.ProjectNetworkPolicyList {
				return &managementcattleiov3.ProjectNetworkPolicyList{}
			},
		),
	}
}
