// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ProjectRoleTemplateBindingsGetter has a method to return a ProjectRoleTemplateBindingInterface.
// A group's client should implement this interface.
type ProjectRoleTemplateBindingsGetter interface {
	ProjectRoleTemplateBindings(namespace string) ProjectRoleTemplateBindingInterface
}

// ProjectRoleTemplateBindingInterface has methods to work with ProjectRoleTemplateBinding resources.
type ProjectRoleTemplateBindingInterface interface {
	Create(ctx context.Context, projectRoleTemplateBinding *managementcattleiov3.ProjectRoleTemplateBinding, opts v1.CreateOptions) (*managementcattleiov3.ProjectRoleTemplateBinding, error)
	Update(ctx context.Context, projectRoleTemplateBinding *managementcattleiov3.ProjectRoleTemplateBinding, opts v1.UpdateOptions) (*managementcattleiov3.ProjectRoleTemplateBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.ProjectRoleTemplateBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.ProjectRoleTemplateBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.ProjectRoleTemplateBinding, err error)
	ProjectRoleTemplateBindingExpansion
}

// projectRoleTemplateBindings implements ProjectRoleTemplateBindingInterface
type projectRoleTemplateBindings struct {
	*gentype.ClientWithList[*managementcattleiov3.ProjectRoleTemplateBinding, *managementcattleiov3.ProjectRoleTemplateBindingList]
}

// newProjectRoleTemplateBindings returns a ProjectRoleTemplateBindings
func newProjectRoleTemplateBindings(c *ManagementV3Client, namespace string) *projectRoleTemplateBindings {
	return &projectRoleTemplateBindings{
		gentype.NewClientWithList[*managementcattleiov3.ProjectRoleTemplateBinding, *managementcattleiov3.ProjectRoleTemplateBindingList](
			"projectroletemplatebindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *managementcattleiov3.ProjectRoleTemplateBinding {
				return &managementcattleiov3.ProjectRoleTemplateBinding{}
			},
			func() *managementcattleiov3.ProjectRoleTemplateBindingList {
				return &managementcattleiov3.ProjectRoleTemplateBindingList{}
			},
		),
	}
}
