// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ProxyEndpointsGetter has a method to return a ProxyEndpointInterface.
// A group's client should implement this interface.
type ProxyEndpointsGetter interface {
	ProxyEndpoints() ProxyEndpointInterface
}

// ProxyEndpointInterface has methods to work with ProxyEndpoint resources.
type ProxyEndpointInterface interface {
	Create(ctx context.Context, proxyEndpoint *managementcattleiov3.ProxyEndpoint, opts v1.CreateOptions) (*managementcattleiov3.ProxyEndpoint, error)
	Update(ctx context.Context, proxyEndpoint *managementcattleiov3.ProxyEndpoint, opts v1.UpdateOptions) (*managementcattleiov3.ProxyEndpoint, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, proxyEndpoint *managementcattleiov3.ProxyEndpoint, opts v1.UpdateOptions) (*managementcattleiov3.ProxyEndpoint, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.ProxyEndpoint, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.ProxyEndpointList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.ProxyEndpoint, err error)
	ProxyEndpointExpansion
}

// proxyEndpoints implements ProxyEndpointInterface
type proxyEndpoints struct {
	*gentype.ClientWithList[*managementcattleiov3.ProxyEndpoint, *managementcattleiov3.ProxyEndpointList]
}

// newProxyEndpoints returns a ProxyEndpoints
func newProxyEndpoints(c *ManagementV3Client) *proxyEndpoints {
	return &proxyEndpoints{
		gentype.NewClientWithList[*managementcattleiov3.ProxyEndpoint, *managementcattleiov3.ProxyEndpointList](
			"proxyendpoints",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.ProxyEndpoint { return &managementcattleiov3.ProxyEndpoint{} },
			func() *managementcattleiov3.ProxyEndpointList { return &managementcattleiov3.ProxyEndpointList{} },
		),
	}
}
