// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RoleTemplatesGetter has a method to return a RoleTemplateInterface.
// A group's client should implement this interface.
type RoleTemplatesGetter interface {
	RoleTemplates() RoleTemplateInterface
}

// RoleTemplateInterface has methods to work with RoleTemplate resources.
type RoleTemplateInterface interface {
	Create(ctx context.Context, roleTemplate *managementcattleiov3.RoleTemplate, opts v1.CreateOptions) (*managementcattleiov3.RoleTemplate, error)
	Update(ctx context.Context, roleTemplate *managementcattleiov3.RoleTemplate, opts v1.UpdateOptions) (*managementcattleiov3.RoleTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.RoleTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.RoleTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.RoleTemplate, err error)
	RoleTemplateExpansion
}

// roleTemplates implements RoleTemplateInterface
type roleTemplates struct {
	*gentype.ClientWithList[*managementcattleiov3.RoleTemplate, *managementcattleiov3.RoleTemplateList]
}

// newRoleTemplates returns a RoleTemplates
func newRoleTemplates(c *ManagementV3Client) *roleTemplates {
	return &roleTemplates{
		gentype.NewClientWithList[*managementcattleiov3.RoleTemplate, *managementcattleiov3.RoleTemplateList](
			"roletemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.RoleTemplate { return &managementcattleiov3.RoleTemplate{} },
			func() *managementcattleiov3.RoleTemplateList { return &managementcattleiov3.RoleTemplateList{} },
		),
	}
}
