// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SamlTokensGetter has a method to return a SamlTokenInterface.
// A group's client should implement this interface.
type SamlTokensGetter interface {
	SamlTokens(namespace string) SamlTokenInterface
}

// SamlTokenInterface has methods to work with SamlToken resources.
type SamlTokenInterface interface {
	Create(ctx context.Context, samlToken *managementcattleiov3.SamlToken, opts v1.CreateOptions) (*managementcattleiov3.SamlToken, error)
	Update(ctx context.Context, samlToken *managementcattleiov3.SamlToken, opts v1.UpdateOptions) (*managementcattleiov3.SamlToken, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.SamlToken, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.SamlTokenList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.SamlToken, err error)
	SamlTokenExpansion
}

// samlTokens implements SamlTokenInterface
type samlTokens struct {
	*gentype.ClientWithList[*managementcattleiov3.SamlToken, *managementcattleiov3.SamlTokenList]
}

// newSamlTokens returns a SamlTokens
func newSamlTokens(c *ManagementV3Client, namespace string) *samlTokens {
	return &samlTokens{
		gentype.NewClientWithList[*managementcattleiov3.SamlToken, *managementcattleiov3.SamlTokenList](
			"samltokens",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *managementcattleiov3.SamlToken { return &managementcattleiov3.SamlToken{} },
			func() *managementcattleiov3.SamlTokenList { return &managementcattleiov3.SamlTokenList{} },
		),
	}
}
