// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SamlProvidersGetter has a method to return a SamlProviderInterface.
// A group's client should implement this interface.
type SamlProvidersGetter interface {
	SamlProviders() SamlProviderInterface
}

// SamlProviderInterface has methods to work with SamlProvider resources.
type SamlProviderInterface interface {
	Create(ctx context.Context, samlProvider *managementcattleiov3.SamlProvider, opts v1.CreateOptions) (*managementcattleiov3.SamlProvider, error)
	Update(ctx context.Context, samlProvider *managementcattleiov3.SamlProvider, opts v1.UpdateOptions) (*managementcattleiov3.SamlProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.SamlProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.SamlProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.SamlProvider, err error)
	SamlProviderExpansion
}

// samlProviders implements SamlProviderInterface
type samlProviders struct {
	*gentype.ClientWithList[*managementcattleiov3.SamlProvider, *managementcattleiov3.SamlProviderList]
}

// newSamlProviders returns a SamlProviders
func newSamlProviders(c *ManagementV3Client) *samlProviders {
	return &samlProviders{
		gentype.NewClientWithList[*managementcattleiov3.SamlProvider, *managementcattleiov3.SamlProviderList](
			"samlproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.SamlProvider { return &managementcattleiov3.SamlProvider{} },
			func() *managementcattleiov3.SamlProviderList { return &managementcattleiov3.SamlProviderList{} },
		),
	}
}
