// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SettingsGetter has a method to return a SettingInterface.
// A group's client should implement this interface.
type SettingsGetter interface {
	Settings() SettingInterface
}

// SettingInterface has methods to work with Setting resources.
type SettingInterface interface {
	Create(ctx context.Context, setting *managementcattleiov3.Setting, opts v1.CreateOptions) (*managementcattleiov3.Setting, error)
	Update(ctx context.Context, setting *managementcattleiov3.Setting, opts v1.UpdateOptions) (*managementcattleiov3.Setting, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.Setting, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.SettingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.Setting, err error)
	SettingExpansion
}

// settings implements SettingInterface
type settings struct {
	*gentype.ClientWithList[*managementcattleiov3.Setting, *managementcattleiov3.SettingList]
}

// newSettings returns a Settings
func newSettings(c *ManagementV3Client) *settings {
	return &settings{
		gentype.NewClientWithList[*managementcattleiov3.Setting, *managementcattleiov3.SettingList](
			"settings",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.Setting { return &managementcattleiov3.Setting{} },
			func() *managementcattleiov3.SettingList { return &managementcattleiov3.SettingList{} },
		),
	}
}
