// Code generated by client-gen. DO NOT EDIT.

package v3

import (
	context "context"

	managementcattleiov3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	scheme "github.com/rancher/rancher/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// UserAttributesGetter has a method to return a UserAttributeInterface.
// A group's client should implement this interface.
type UserAttributesGetter interface {
	UserAttributes() UserAttributeInterface
}

// UserAttributeInterface has methods to work with UserAttribute resources.
type UserAttributeInterface interface {
	Create(ctx context.Context, userAttribute *managementcattleiov3.UserAttribute, opts v1.CreateOptions) (*managementcattleiov3.UserAttribute, error)
	Update(ctx context.Context, userAttribute *managementcattleiov3.UserAttribute, opts v1.UpdateOptions) (*managementcattleiov3.UserAttribute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*managementcattleiov3.UserAttribute, error)
	List(ctx context.Context, opts v1.ListOptions) (*managementcattleiov3.UserAttributeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *managementcattleiov3.UserAttribute, err error)
	UserAttributeExpansion
}

// userAttributes implements UserAttributeInterface
type userAttributes struct {
	*gentype.ClientWithList[*managementcattleiov3.UserAttribute, *managementcattleiov3.UserAttributeList]
}

// newUserAttributes returns a UserAttributes
func newUserAttributes(c *ManagementV3Client) *userAttributes {
	return &userAttributes{
		gentype.NewClientWithList[*managementcattleiov3.UserAttribute, *managementcattleiov3.UserAttributeList](
			"userattributes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *managementcattleiov3.UserAttribute { return &managementcattleiov3.UserAttribute{} },
			func() *managementcattleiov3.UserAttributeList { return &managementcattleiov3.UserAttributeList{} },
		),
	}
}
