// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeRancherUserNotifications implements RancherUserNotificationInterface
type fakeRancherUserNotifications struct {
	*gentype.FakeClientWithList[*v3.RancherUserNotification, *v3.RancherUserNotificationList]
	Fake *FakeManagementV3
}

func newFakeRancherUserNotifications(fake *FakeManagementV3) managementcattleiov3.RancherUserNotificationInterface {
	return &fakeRancherUserNotifications{
		gentype.NewFakeClientWithList[*v3.RancherUserNotification, *v3.RancherUserNotificationList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("rancherusernotifications"),
			v3.SchemeGroupVersion.WithKind("RancherUserNotification"),
			func() *v3.RancherUserNotification { return &v3.RancherUserNotification{} },
			func() *v3.RancherUserNotificationList { return &v3.RancherUserNotificationList{} },
			func(dst, src *v3.RancherUserNotificationList) { dst.ListMeta = src.ListMeta },
			func(list *v3.RancherUserNotificationList) []*v3.RancherUserNotification {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.RancherUserNotificationList, items []*v3.RancherUserNotification) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
