// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeGlobalRoles implements GlobalRoleInterface
type fakeGlobalRoles struct {
	*gentype.FakeClientWithList[*v3.GlobalRole, *v3.GlobalRoleList]
	Fake *FakeManagementV3
}

func newFakeGlobalRoles(fake *FakeManagementV3) managementcattleiov3.GlobalRoleInterface {
	return &fakeGlobalRoles{
		gentype.NewFakeClientWithList[*v3.GlobalRole, *v3.GlobalRoleList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("globalroles"),
			v3.SchemeGroupVersion.WithKind("GlobalRole"),
			func() *v3.GlobalRole { return &v3.GlobalRole{} },
			func() *v3.GlobalRoleList { return &v3.GlobalRoleList{} },
			func(dst, src *v3.GlobalRoleList) { dst.ListMeta = src.ListMeta },
			func(list *v3.GlobalRoleList) []*v3.GlobalRole { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.GlobalRoleList, items []*v3.GlobalRole) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
