// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeNodeDrivers implements NodeDriverInterface
type fakeNodeDrivers struct {
	*gentype.FakeClientWithList[*v3.NodeDriver, *v3.NodeDriverList]
	Fake *FakeManagementV3
}

func newFakeNodeDrivers(fake *FakeManagementV3) managementcattleiov3.NodeDriverInterface {
	return &fakeNodeDrivers{
		gentype.NewFakeClientWithList[*v3.NodeDriver, *v3.NodeDriverList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("nodedrivers"),
			v3.SchemeGroupVersion.WithKind("NodeDriver"),
			func() *v3.NodeDriver { return &v3.NodeDriver{} },
			func() *v3.NodeDriverList { return &v3.NodeDriverList{} },
			func(dst, src *v3.NodeDriverList) { dst.ListMeta = src.ListMeta },
			func(list *v3.NodeDriverList) []*v3.NodeDriver { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.NodeDriverList, items []*v3.NodeDriver) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
