// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeProxyEndpoints implements ProxyEndpointInterface
type fakeProxyEndpoints struct {
	*gentype.FakeClientWithList[*v3.ProxyEndpoint, *v3.ProxyEndpointList]
	Fake *FakeManagementV3
}

func newFakeProxyEndpoints(fake *FakeManagementV3) managementcattleiov3.ProxyEndpointInterface {
	return &fakeProxyEndpoints{
		gentype.NewFakeClientWithList[*v3.ProxyEndpoint, *v3.ProxyEndpointList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("proxyendpoints"),
			v3.SchemeGroupVersion.WithKind("ProxyEndpoint"),
			func() *v3.ProxyEndpoint { return &v3.ProxyEndpoint{} },
			func() *v3.ProxyEndpointList { return &v3.ProxyEndpointList{} },
			func(dst, src *v3.ProxyEndpointList) { dst.ListMeta = src.ListMeta },
			func(list *v3.ProxyEndpointList) []*v3.ProxyEndpoint { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.ProxyEndpointList, items []*v3.ProxyEndpoint) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
