// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeGithubAppProviders implements GithubAppProviderInterface
type fakeGithubAppProviders struct {
	*gentype.FakeClientWithList[*v3.GithubAppProvider, *v3.GithubAppProviderList]
	Fake *FakeManagementV3
}

func newFakeGithubAppProviders(fake *FakeManagementV3) managementcattleiov3.GithubAppProviderInterface {
	return &fakeGithubAppProviders{
		gentype.NewFakeClientWithList[*v3.GithubAppProvider, *v3.GithubAppProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("githubappproviders"),
			v3.SchemeGroupVersion.WithKind("GithubAppProvider"),
			func() *v3.GithubAppProvider { return &v3.GithubAppProvider{} },
			func() *v3.GithubAppProviderList { return &v3.GithubAppProviderList{} },
			func(dst, src *v3.GithubAppProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.GithubAppProviderList) []*v3.GithubAppProvider {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.GithubAppProviderList, items []*v3.GithubAppProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
