// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeGithubAppConfigs implements GithubAppConfigInterface
type fakeGithubAppConfigs struct {
	*gentype.FakeClientWithList[*v3.GithubAppConfig, *v3.GithubAppConfigList]
	Fake *FakeManagementV3
}

func newFakeGithubAppConfigs(fake *FakeManagementV3) managementcattleiov3.GithubAppConfigInterface {
	return &fakeGithubAppConfigs{
		gentype.NewFakeClientWithList[*v3.GithubAppConfig, *v3.GithubAppConfigList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("githubappconfigs"),
			v3.SchemeGroupVersion.WithKind("GithubAppConfig"),
			func() *v3.GithubAppConfig { return &v3.GithubAppConfig{} },
			func() *v3.GithubAppConfigList { return &v3.GithubAppConfigList{} },
			func(dst, src *v3.GithubAppConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v3.GithubAppConfigList) []*v3.GithubAppConfig { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.GithubAppConfigList, items []*v3.GithubAppConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
