// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusters implements ClusterInterface
type fakeClusters struct {
	*gentype.FakeClientWithList[*v3.Cluster, *v3.ClusterList]
	Fake *FakeManagementV3
}

func newFakeClusters(fake *FakeManagementV3) managementcattleiov3.ClusterInterface {
	return &fakeClusters{
		gentype.NewFakeClientWithList[*v3.Cluster, *v3.ClusterList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("clusters"),
			v3.SchemeGroupVersion.WithKind("Cluster"),
			func() *v3.Cluster { return &v3.Cluster{} },
			func() *v3.ClusterList { return &v3.ClusterList{} },
			func(dst, src *v3.ClusterList) { dst.ListMeta = src.ListMeta },
			func(list *v3.ClusterList) []*v3.Cluster { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.ClusterList, items []*v3.Cluster) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
