// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakePodSecurityAdmissionConfigurationTemplates implements PodSecurityAdmissionConfigurationTemplateInterface
type fakePodSecurityAdmissionConfigurationTemplates struct {
	*gentype.FakeClientWithList[*v3.PodSecurityAdmissionConfigurationTemplate, *v3.PodSecurityAdmissionConfigurationTemplateList]
	Fake *FakeManagementV3
}

func newFakePodSecurityAdmissionConfigurationTemplates(fake *FakeManagementV3) managementcattleiov3.PodSecurityAdmissionConfigurationTemplateInterface {
	return &fakePodSecurityAdmissionConfigurationTemplates{
		gentype.NewFakeClientWithList[*v3.PodSecurityAdmissionConfigurationTemplate, *v3.PodSecurityAdmissionConfigurationTemplateList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("podsecurityadmissionconfigurationtemplates"),
			v3.SchemeGroupVersion.WithKind("PodSecurityAdmissionConfigurationTemplate"),
			func() *v3.PodSecurityAdmissionConfigurationTemplate {
				return &v3.PodSecurityAdmissionConfigurationTemplate{}
			},
			func() *v3.PodSecurityAdmissionConfigurationTemplateList {
				return &v3.PodSecurityAdmissionConfigurationTemplateList{}
			},
			func(dst, src *v3.PodSecurityAdmissionConfigurationTemplateList) { dst.ListMeta = src.ListMeta },
			func(list *v3.PodSecurityAdmissionConfigurationTemplateList) []*v3.PodSecurityAdmissionConfigurationTemplate {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.PodSecurityAdmissionConfigurationTemplateList, items []*v3.PodSecurityAdmissionConfigurationTemplate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
