// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeAuthConfigs implements AuthConfigInterface
type fakeAuthConfigs struct {
	*gentype.FakeClientWithList[*v3.AuthConfig, *v3.AuthConfigList]
	Fake *FakeManagementV3
}

func newFakeAuthConfigs(fake *FakeManagementV3) managementcattleiov3.AuthConfigInterface {
	return &fakeAuthConfigs{
		gentype.NewFakeClientWithList[*v3.AuthConfig, *v3.AuthConfigList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("authconfigs"),
			v3.SchemeGroupVersion.WithKind("AuthConfig"),
			func() *v3.AuthConfig { return &v3.AuthConfig{} },
			func() *v3.AuthConfigList { return &v3.AuthConfigList{} },
			func(dst, src *v3.AuthConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v3.AuthConfigList) []*v3.AuthConfig { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.AuthConfigList, items []*v3.AuthConfig) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
