// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeUserAttributes implements UserAttributeInterface
type fakeUserAttributes struct {
	*gentype.FakeClientWithList[*v3.UserAttribute, *v3.UserAttributeList]
	Fake *FakeManagementV3
}

func newFakeUserAttributes(fake *FakeManagementV3) managementcattleiov3.UserAttributeInterface {
	return &fakeUserAttributes{
		gentype.NewFakeClientWithList[*v3.UserAttribute, *v3.UserAttributeList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("userattributes"),
			v3.SchemeGroupVersion.WithKind("UserAttribute"),
			func() *v3.UserAttribute { return &v3.UserAttribute{} },
			func() *v3.UserAttributeList { return &v3.UserAttributeList{} },
			func(dst, src *v3.UserAttributeList) { dst.ListMeta = src.ListMeta },
			func(list *v3.UserAttributeList) []*v3.UserAttribute { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.UserAttributeList, items []*v3.UserAttribute) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
