// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterRegistrationTokens implements ClusterRegistrationTokenInterface
type fakeClusterRegistrationTokens struct {
	*gentype.FakeClientWithList[*v3.ClusterRegistrationToken, *v3.ClusterRegistrationTokenList]
	Fake *FakeManagementV3
}

func newFakeClusterRegistrationTokens(fake *FakeManagementV3, namespace string) managementcattleiov3.ClusterRegistrationTokenInterface {
	return &fakeClusterRegistrationTokens{
		gentype.NewFakeClientWithList[*v3.ClusterRegistrationToken, *v3.ClusterRegistrationTokenList](
			fake.Fake,
			namespace,
			v3.SchemeGroupVersion.WithResource("clusterregistrationtokens"),
			v3.SchemeGroupVersion.WithKind("ClusterRegistrationToken"),
			func() *v3.ClusterRegistrationToken { return &v3.ClusterRegistrationToken{} },
			func() *v3.ClusterRegistrationTokenList { return &v3.ClusterRegistrationTokenList{} },
			func(dst, src *v3.ClusterRegistrationTokenList) { dst.ListMeta = src.ListMeta },
			func(list *v3.ClusterRegistrationTokenList) []*v3.ClusterRegistrationToken {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.ClusterRegistrationTokenList, items []*v3.ClusterRegistrationToken) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
