// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeSamlProviders implements SamlProviderInterface
type fakeSamlProviders struct {
	*gentype.FakeClientWithList[*v3.SamlProvider, *v3.SamlProviderList]
	Fake *FakeManagementV3
}

func newFakeSamlProviders(fake *FakeManagementV3) managementcattleiov3.SamlProviderInterface {
	return &fakeSamlProviders{
		gentype.NewFakeClientWithList[*v3.SamlProvider, *v3.SamlProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("samlproviders"),
			v3.SchemeGroupVersion.WithKind("SamlProvider"),
			func() *v3.SamlProvider { return &v3.SamlProvider{} },
			func() *v3.SamlProviderList { return &v3.SamlProviderList{} },
			func(dst, src *v3.SamlProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.SamlProviderList) []*v3.SamlProvider { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.SamlProviderList, items []*v3.SamlProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
