// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeAuthTokens implements AuthTokenInterface
type fakeAuthTokens struct {
	*gentype.FakeClientWithList[*v3.AuthToken, *v3.AuthTokenList]
	Fake *FakeManagementV3
}

func newFakeAuthTokens(fake *FakeManagementV3) managementcattleiov3.AuthTokenInterface {
	return &fakeAuthTokens{
		gentype.NewFakeClientWithList[*v3.AuthToken, *v3.AuthTokenList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("authtokens"),
			v3.SchemeGroupVersion.WithKind("AuthToken"),
			func() *v3.AuthToken { return &v3.AuthToken{} },
			func() *v3.AuthTokenList { return &v3.AuthTokenList{} },
			func(dst, src *v3.AuthTokenList) { dst.ListMeta = src.ListMeta },
			func(list *v3.AuthTokenList) []*v3.AuthToken { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.AuthTokenList, items []*v3.AuthToken) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
