// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeOIDCProviders implements OIDCProviderInterface
type fakeOIDCProviders struct {
	*gentype.FakeClientWithList[*v3.OIDCProvider, *v3.OIDCProviderList]
	Fake *FakeManagementV3
}

func newFakeOIDCProviders(fake *FakeManagementV3) managementcattleiov3.OIDCProviderInterface {
	return &fakeOIDCProviders{
		gentype.NewFakeClientWithList[*v3.OIDCProvider, *v3.OIDCProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("oidcproviders"),
			v3.SchemeGroupVersion.WithKind("OIDCProvider"),
			func() *v3.OIDCProvider { return &v3.OIDCProvider{} },
			func() *v3.OIDCProviderList { return &v3.OIDCProviderList{} },
			func(dst, src *v3.OIDCProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.OIDCProviderList) []*v3.OIDCProvider { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.OIDCProviderList, items []*v3.OIDCProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
