// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeKontainerDrivers implements KontainerDriverInterface
type fakeKontainerDrivers struct {
	*gentype.FakeClientWithList[*v3.KontainerDriver, *v3.KontainerDriverList]
	Fake *FakeManagementV3
}

func newFakeKontainerDrivers(fake *FakeManagementV3) managementcattleiov3.KontainerDriverInterface {
	return &fakeKontainerDrivers{
		gentype.NewFakeClientWithList[*v3.KontainerDriver, *v3.KontainerDriverList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("kontainerdrivers"),
			v3.SchemeGroupVersion.WithKind("KontainerDriver"),
			func() *v3.KontainerDriver { return &v3.KontainerDriver{} },
			func() *v3.KontainerDriverList { return &v3.KontainerDriverList{} },
			func(dst, src *v3.KontainerDriverList) { dst.ListMeta = src.ListMeta },
			func(list *v3.KontainerDriverList) []*v3.KontainerDriver { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.KontainerDriverList, items []*v3.KontainerDriver) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
