// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeGroups implements GroupInterface
type fakeGroups struct {
	*gentype.FakeClientWithList[*v3.Group, *v3.GroupList]
	Fake *FakeManagementV3
}

func newFakeGroups(fake *FakeManagementV3) managementcattleiov3.GroupInterface {
	return &fakeGroups{
		gentype.NewFakeClientWithList[*v3.Group, *v3.GroupList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("groups"),
			v3.SchemeGroupVersion.WithKind("Group"),
			func() *v3.Group { return &v3.Group{} },
			func() *v3.GroupList { return &v3.GroupList{} },
			func(dst, src *v3.GroupList) { dst.ListMeta = src.ListMeta },
			func(list *v3.GroupList) []*v3.Group { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.GroupList, items []*v3.Group) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
