// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeGroupMembers implements GroupMemberInterface
type fakeGroupMembers struct {
	*gentype.FakeClientWithList[*v3.GroupMember, *v3.GroupMemberList]
	Fake *FakeManagementV3
}

func newFakeGroupMembers(fake *FakeManagementV3) managementcattleiov3.GroupMemberInterface {
	return &fakeGroupMembers{
		gentype.NewFakeClientWithList[*v3.GroupMember, *v3.GroupMemberList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("groupmembers"),
			v3.SchemeGroupVersion.WithKind("GroupMember"),
			func() *v3.GroupMember { return &v3.GroupMember{} },
			func() *v3.GroupMemberList { return &v3.GroupMemberList{} },
			func(dst, src *v3.GroupMemberList) { dst.ListMeta = src.ListMeta },
			func(list *v3.GroupMemberList) []*v3.GroupMember { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.GroupMemberList, items []*v3.GroupMember) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
