// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeSamlTokens implements SamlTokenInterface
type fakeSamlTokens struct {
	*gentype.FakeClientWithList[*v3.SamlToken, *v3.SamlTokenList]
	Fake *FakeManagementV3
}

func newFakeSamlTokens(fake *FakeManagementV3, namespace string) managementcattleiov3.SamlTokenInterface {
	return &fakeSamlTokens{
		gentype.NewFakeClientWithList[*v3.SamlToken, *v3.SamlTokenList](
			fake.Fake,
			namespace,
			v3.SchemeGroupVersion.WithResource("samltokens"),
			v3.SchemeGroupVersion.WithKind("SamlToken"),
			func() *v3.SamlToken { return &v3.SamlToken{} },
			func() *v3.SamlTokenList { return &v3.SamlTokenList{} },
			func(dst, src *v3.SamlTokenList) { dst.ListMeta = src.ListMeta },
			func(list *v3.SamlTokenList) []*v3.SamlToken { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.SamlTokenList, items []*v3.SamlToken) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
