// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeUsers implements UserInterface
type fakeUsers struct {
	*gentype.FakeClientWithList[*v3.User, *v3.UserList]
	Fake *FakeManagementV3
}

func newFakeUsers(fake *FakeManagementV3) managementcattleiov3.UserInterface {
	return &fakeUsers{
		gentype.NewFakeClientWithList[*v3.User, *v3.UserList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("users"),
			v3.SchemeGroupVersion.WithKind("User"),
			func() *v3.User { return &v3.User{} },
			func() *v3.UserList { return &v3.UserList{} },
			func(dst, src *v3.UserList) { dst.ListMeta = src.ListMeta },
			func(list *v3.UserList) []*v3.User { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.UserList, items []*v3.User) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
