// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakePreferences implements PreferenceInterface
type fakePreferences struct {
	*gentype.FakeClientWithList[*v3.Preference, *v3.PreferenceList]
	Fake *FakeManagementV3
}

func newFakePreferences(fake *FakeManagementV3, namespace string) managementcattleiov3.PreferenceInterface {
	return &fakePreferences{
		gentype.NewFakeClientWithList[*v3.Preference, *v3.PreferenceList](
			fake.Fake,
			namespace,
			v3.SchemeGroupVersion.WithResource("preferences"),
			v3.SchemeGroupVersion.WithKind("Preference"),
			func() *v3.Preference { return &v3.Preference{} },
			func() *v3.PreferenceList { return &v3.PreferenceList{} },
			func(dst, src *v3.PreferenceList) { dst.ListMeta = src.ListMeta },
			func(list *v3.PreferenceList) []*v3.Preference { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.PreferenceList, items []*v3.Preference) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
