// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeGenericOIDCProviders implements GenericOIDCProviderInterface
type fakeGenericOIDCProviders struct {
	*gentype.FakeClientWithList[*v3.GenericOIDCProvider, *v3.GenericOIDCProviderList]
	Fake *FakeManagementV3
}

func newFakeGenericOIDCProviders(fake *FakeManagementV3) managementcattleiov3.GenericOIDCProviderInterface {
	return &fakeGenericOIDCProviders{
		gentype.NewFakeClientWithList[*v3.GenericOIDCProvider, *v3.GenericOIDCProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("genericoidcproviders"),
			v3.SchemeGroupVersion.WithKind("GenericOIDCProvider"),
			func() *v3.GenericOIDCProvider { return &v3.GenericOIDCProvider{} },
			func() *v3.GenericOIDCProviderList { return &v3.GenericOIDCProviderList{} },
			func(dst, src *v3.GenericOIDCProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.GenericOIDCProviderList) []*v3.GenericOIDCProvider {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.GenericOIDCProviderList, items []*v3.GenericOIDCProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
