// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeCognitoProviders implements CognitoProviderInterface
type fakeCognitoProviders struct {
	*gentype.FakeClientWithList[*v3.CognitoProvider, *v3.CognitoProviderList]
	Fake *FakeManagementV3
}

func newFakeCognitoProviders(fake *FakeManagementV3) managementcattleiov3.CognitoProviderInterface {
	return &fakeCognitoProviders{
		gentype.NewFakeClientWithList[*v3.CognitoProvider, *v3.CognitoProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("cognitoproviders"),
			v3.SchemeGroupVersion.WithKind("CognitoProvider"),
			func() *v3.CognitoProvider { return &v3.CognitoProvider{} },
			func() *v3.CognitoProviderList { return &v3.CognitoProviderList{} },
			func(dst, src *v3.CognitoProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.CognitoProviderList) []*v3.CognitoProvider { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.CognitoProviderList, items []*v3.CognitoProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
