// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeComposeConfigs implements ComposeConfigInterface
type fakeComposeConfigs struct {
	*gentype.FakeClientWithList[*v3.ComposeConfig, *v3.ComposeConfigList]
	Fake *FakeManagementV3
}

func newFakeComposeConfigs(fake *FakeManagementV3) managementcattleiov3.ComposeConfigInterface {
	return &fakeComposeConfigs{
		gentype.NewFakeClientWithList[*v3.ComposeConfig, *v3.ComposeConfigList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("composeconfigs"),
			v3.SchemeGroupVersion.WithKind("ComposeConfig"),
			func() *v3.ComposeConfig { return &v3.ComposeConfig{} },
			func() *v3.ComposeConfigList { return &v3.ComposeConfigList{} },
			func(dst, src *v3.ComposeConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v3.ComposeConfigList) []*v3.ComposeConfig { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.ComposeConfigList, items []*v3.ComposeConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
