// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeLocalProviders implements LocalProviderInterface
type fakeLocalProviders struct {
	*gentype.FakeClientWithList[*v3.LocalProvider, *v3.LocalProviderList]
	Fake *FakeManagementV3
}

func newFakeLocalProviders(fake *FakeManagementV3) managementcattleiov3.LocalProviderInterface {
	return &fakeLocalProviders{
		gentype.NewFakeClientWithList[*v3.LocalProvider, *v3.LocalProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("localproviders"),
			v3.SchemeGroupVersion.WithKind("LocalProvider"),
			func() *v3.LocalProvider { return &v3.LocalProvider{} },
			func() *v3.LocalProviderList { return &v3.LocalProviderList{} },
			func(dst, src *v3.LocalProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.LocalProviderList) []*v3.LocalProvider { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.LocalProviderList, items []*v3.LocalProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
