// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeGlobalRoleBindings implements GlobalRoleBindingInterface
type fakeGlobalRoleBindings struct {
	*gentype.FakeClientWithList[*v3.GlobalRoleBinding, *v3.GlobalRoleBindingList]
	Fake *FakeManagementV3
}

func newFakeGlobalRoleBindings(fake *FakeManagementV3) managementcattleiov3.GlobalRoleBindingInterface {
	return &fakeGlobalRoleBindings{
		gentype.NewFakeClientWithList[*v3.GlobalRoleBinding, *v3.GlobalRoleBindingList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("globalrolebindings"),
			v3.SchemeGroupVersion.WithKind("GlobalRoleBinding"),
			func() *v3.GlobalRoleBinding { return &v3.GlobalRoleBinding{} },
			func() *v3.GlobalRoleBindingList { return &v3.GlobalRoleBindingList{} },
			func(dst, src *v3.GlobalRoleBindingList) { dst.ListMeta = src.ListMeta },
			func(list *v3.GlobalRoleBindingList) []*v3.GlobalRoleBinding {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.GlobalRoleBindingList, items []*v3.GlobalRoleBinding) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
