// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeOpenLdapProviders implements OpenLdapProviderInterface
type fakeOpenLdapProviders struct {
	*gentype.FakeClientWithList[*v3.OpenLdapProvider, *v3.OpenLdapProviderList]
	Fake *FakeManagementV3
}

func newFakeOpenLdapProviders(fake *FakeManagementV3) managementcattleiov3.OpenLdapProviderInterface {
	return &fakeOpenLdapProviders{
		gentype.NewFakeClientWithList[*v3.OpenLdapProvider, *v3.OpenLdapProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("openldapproviders"),
			v3.SchemeGroupVersion.WithKind("OpenLdapProvider"),
			func() *v3.OpenLdapProvider { return &v3.OpenLdapProvider{} },
			func() *v3.OpenLdapProviderList { return &v3.OpenLdapProviderList{} },
			func(dst, src *v3.OpenLdapProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.OpenLdapProviderList) []*v3.OpenLdapProvider { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.OpenLdapProviderList, items []*v3.OpenLdapProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
