// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeCloudCredentials implements CloudCredentialInterface
type fakeCloudCredentials struct {
	*gentype.FakeClientWithList[*v3.CloudCredential, *v3.CloudCredentialList]
	Fake *FakeManagementV3
}

func newFakeCloudCredentials(fake *FakeManagementV3, namespace string) managementcattleiov3.CloudCredentialInterface {
	return &fakeCloudCredentials{
		gentype.NewFakeClientWithList[*v3.CloudCredential, *v3.CloudCredentialList](
			fake.Fake,
			namespace,
			v3.SchemeGroupVersion.WithResource("cloudcredentials"),
			v3.SchemeGroupVersion.WithKind("CloudCredential"),
			func() *v3.CloudCredential { return &v3.CloudCredential{} },
			func() *v3.CloudCredentialList { return &v3.CloudCredentialList{} },
			func(dst, src *v3.CloudCredentialList) { dst.ListMeta = src.ListMeta },
			func(list *v3.CloudCredentialList) []*v3.CloudCredential { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.CloudCredentialList, items []*v3.CloudCredential) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
