// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterProxyConfigs implements ClusterProxyConfigInterface
type fakeClusterProxyConfigs struct {
	*gentype.FakeClientWithList[*v3.ClusterProxyConfig, *v3.ClusterProxyConfigList]
	Fake *FakeManagementV3
}

func newFakeClusterProxyConfigs(fake *FakeManagementV3, namespace string) managementcattleiov3.ClusterProxyConfigInterface {
	return &fakeClusterProxyConfigs{
		gentype.NewFakeClientWithList[*v3.ClusterProxyConfig, *v3.ClusterProxyConfigList](
			fake.Fake,
			namespace,
			v3.SchemeGroupVersion.WithResource("clusterproxyconfigs"),
			v3.SchemeGroupVersion.WithKind("ClusterProxyConfig"),
			func() *v3.ClusterProxyConfig { return &v3.ClusterProxyConfig{} },
			func() *v3.ClusterProxyConfigList { return &v3.ClusterProxyConfigList{} },
			func(dst, src *v3.ClusterProxyConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v3.ClusterProxyConfigList) []*v3.ClusterProxyConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.ClusterProxyConfigList, items []*v3.ClusterProxyConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
