// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeGoogleOAuthProviders implements GoogleOAuthProviderInterface
type fakeGoogleOAuthProviders struct {
	*gentype.FakeClientWithList[*v3.GoogleOAuthProvider, *v3.GoogleOAuthProviderList]
	Fake *FakeManagementV3
}

func newFakeGoogleOAuthProviders(fake *FakeManagementV3) managementcattleiov3.GoogleOAuthProviderInterface {
	return &fakeGoogleOAuthProviders{
		gentype.NewFakeClientWithList[*v3.GoogleOAuthProvider, *v3.GoogleOAuthProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("googleoauthproviders"),
			v3.SchemeGroupVersion.WithKind("GoogleOAuthProvider"),
			func() *v3.GoogleOAuthProvider { return &v3.GoogleOAuthProvider{} },
			func() *v3.GoogleOAuthProviderList { return &v3.GoogleOAuthProviderList{} },
			func(dst, src *v3.GoogleOAuthProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.GoogleOAuthProviderList) []*v3.GoogleOAuthProvider {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.GoogleOAuthProviderList, items []*v3.GoogleOAuthProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
