// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeActiveDirectoryProviders implements ActiveDirectoryProviderInterface
type fakeActiveDirectoryProviders struct {
	*gentype.FakeClientWithList[*v3.ActiveDirectoryProvider, *v3.ActiveDirectoryProviderList]
	Fake *FakeManagementV3
}

func newFakeActiveDirectoryProviders(fake *FakeManagementV3) managementcattleiov3.ActiveDirectoryProviderInterface {
	return &fakeActiveDirectoryProviders{
		gentype.NewFakeClientWithList[*v3.ActiveDirectoryProvider, *v3.ActiveDirectoryProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("activedirectoryproviders"),
			v3.SchemeGroupVersion.WithKind("ActiveDirectoryProvider"),
			func() *v3.ActiveDirectoryProvider { return &v3.ActiveDirectoryProvider{} },
			func() *v3.ActiveDirectoryProviderList { return &v3.ActiveDirectoryProviderList{} },
			func(dst, src *v3.ActiveDirectoryProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.ActiveDirectoryProviderList) []*v3.ActiveDirectoryProvider {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.ActiveDirectoryProviderList, items []*v3.ActiveDirectoryProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
