// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeOIDCClients implements OIDCClientInterface
type fakeOIDCClients struct {
	*gentype.FakeClientWithList[*v3.OIDCClient, *v3.OIDCClientList]
	Fake *FakeManagementV3
}

func newFakeOIDCClients(fake *FakeManagementV3) managementcattleiov3.OIDCClientInterface {
	return &fakeOIDCClients{
		gentype.NewFakeClientWithList[*v3.OIDCClient, *v3.OIDCClientList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("oidcclients"),
			v3.SchemeGroupVersion.WithKind("OIDCClient"),
			func() *v3.OIDCClient { return &v3.OIDCClient{} },
			func() *v3.OIDCClientList { return &v3.OIDCClientList{} },
			func(dst, src *v3.OIDCClientList) { dst.ListMeta = src.ListMeta },
			func(list *v3.OIDCClientList) []*v3.OIDCClient { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.OIDCClientList, items []*v3.OIDCClient) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
