// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeDynamicSchemas implements DynamicSchemaInterface
type fakeDynamicSchemas struct {
	*gentype.FakeClientWithList[*v3.DynamicSchema, *v3.DynamicSchemaList]
	Fake *FakeManagementV3
}

func newFakeDynamicSchemas(fake *FakeManagementV3) managementcattleiov3.DynamicSchemaInterface {
	return &fakeDynamicSchemas{
		gentype.NewFakeClientWithList[*v3.DynamicSchema, *v3.DynamicSchemaList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("dynamicschemas"),
			v3.SchemeGroupVersion.WithKind("DynamicSchema"),
			func() *v3.DynamicSchema { return &v3.DynamicSchema{} },
			func() *v3.DynamicSchemaList { return &v3.DynamicSchemaList{} },
			func(dst, src *v3.DynamicSchemaList) { dst.ListMeta = src.ListMeta },
			func(list *v3.DynamicSchemaList) []*v3.DynamicSchema { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.DynamicSchemaList, items []*v3.DynamicSchema) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
