// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeProjectNetworkPolicies implements ProjectNetworkPolicyInterface
type fakeProjectNetworkPolicies struct {
	*gentype.FakeClientWithList[*v3.ProjectNetworkPolicy, *v3.ProjectNetworkPolicyList]
	Fake *FakeManagementV3
}

func newFakeProjectNetworkPolicies(fake *FakeManagementV3, namespace string) managementcattleiov3.ProjectNetworkPolicyInterface {
	return &fakeProjectNetworkPolicies{
		gentype.NewFakeClientWithList[*v3.ProjectNetworkPolicy, *v3.ProjectNetworkPolicyList](
			fake.Fake,
			namespace,
			v3.SchemeGroupVersion.WithResource("projectnetworkpolicies"),
			v3.SchemeGroupVersion.WithKind("ProjectNetworkPolicy"),
			func() *v3.ProjectNetworkPolicy { return &v3.ProjectNetworkPolicy{} },
			func() *v3.ProjectNetworkPolicyList { return &v3.ProjectNetworkPolicyList{} },
			func(dst, src *v3.ProjectNetworkPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v3.ProjectNetworkPolicyList) []*v3.ProjectNetworkPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.ProjectNetworkPolicyList, items []*v3.ProjectNetworkPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
