// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeGithubConfigs implements GithubConfigInterface
type fakeGithubConfigs struct {
	*gentype.FakeClientWithList[*v3.GithubConfig, *v3.GithubConfigList]
	Fake *FakeManagementV3
}

func newFakeGithubConfigs(fake *FakeManagementV3) managementcattleiov3.GithubConfigInterface {
	return &fakeGithubConfigs{
		gentype.NewFakeClientWithList[*v3.GithubConfig, *v3.GithubConfigList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("githubconfigs"),
			v3.SchemeGroupVersion.WithKind("GithubConfig"),
			func() *v3.GithubConfig { return &v3.GithubConfig{} },
			func() *v3.GithubConfigList { return &v3.GithubConfigList{} },
			func(dst, src *v3.GithubConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v3.GithubConfigList) []*v3.GithubConfig { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.GithubConfigList, items []*v3.GithubConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
