// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeProjects implements ProjectInterface
type fakeProjects struct {
	*gentype.FakeClientWithList[*v3.Project, *v3.ProjectList]
	Fake *FakeManagementV3
}

func newFakeProjects(fake *FakeManagementV3, namespace string) managementcattleiov3.ProjectInterface {
	return &fakeProjects{
		gentype.NewFakeClientWithList[*v3.Project, *v3.ProjectList](
			fake.Fake,
			namespace,
			v3.SchemeGroupVersion.WithResource("projects"),
			v3.SchemeGroupVersion.WithKind("Project"),
			func() *v3.Project { return &v3.Project{} },
			func() *v3.ProjectList { return &v3.ProjectList{} },
			func(dst, src *v3.ProjectList) { dst.ListMeta = src.ListMeta },
			func(list *v3.ProjectList) []*v3.Project { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.ProjectList, items []*v3.Project) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
