// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeFeatures implements FeatureInterface
type fakeFeatures struct {
	*gentype.FakeClientWithList[*v3.Feature, *v3.FeatureList]
	Fake *FakeManagementV3
}

func newFakeFeatures(fake *FakeManagementV3) managementcattleiov3.FeatureInterface {
	return &fakeFeatures{
		gentype.NewFakeClientWithList[*v3.Feature, *v3.FeatureList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("features"),
			v3.SchemeGroupVersion.WithKind("Feature"),
			func() *v3.Feature { return &v3.Feature{} },
			func() *v3.FeatureList { return &v3.FeatureList{} },
			func(dst, src *v3.FeatureList) { dst.ListMeta = src.ListMeta },
			func(list *v3.FeatureList) []*v3.Feature { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.FeatureList, items []*v3.Feature) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
