// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeSettings implements SettingInterface
type fakeSettings struct {
	*gentype.FakeClientWithList[*v3.Setting, *v3.SettingList]
	Fake *FakeManagementV3
}

func newFakeSettings(fake *FakeManagementV3) managementcattleiov3.SettingInterface {
	return &fakeSettings{
		gentype.NewFakeClientWithList[*v3.Setting, *v3.SettingList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("settings"),
			v3.SchemeGroupVersion.WithKind("Setting"),
			func() *v3.Setting { return &v3.Setting{} },
			func() *v3.SettingList { return &v3.SettingList{} },
			func(dst, src *v3.SettingList) { dst.ListMeta = src.ListMeta },
			func(list *v3.SettingList) []*v3.Setting { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.SettingList, items []*v3.Setting) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
