// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeKeyCloakOIDCProviders implements KeyCloakOIDCProviderInterface
type fakeKeyCloakOIDCProviders struct {
	*gentype.FakeClientWithList[*v3.KeyCloakOIDCProvider, *v3.KeyCloakOIDCProviderList]
	Fake *FakeManagementV3
}

func newFakeKeyCloakOIDCProviders(fake *FakeManagementV3) managementcattleiov3.KeyCloakOIDCProviderInterface {
	return &fakeKeyCloakOIDCProviders{
		gentype.NewFakeClientWithList[*v3.KeyCloakOIDCProvider, *v3.KeyCloakOIDCProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("keycloakoidcproviders"),
			v3.SchemeGroupVersion.WithKind("KeyCloakOIDCProvider"),
			func() *v3.KeyCloakOIDCProvider { return &v3.KeyCloakOIDCProvider{} },
			func() *v3.KeyCloakOIDCProviderList { return &v3.KeyCloakOIDCProviderList{} },
			func(dst, src *v3.KeyCloakOIDCProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.KeyCloakOIDCProviderList) []*v3.KeyCloakOIDCProvider {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.KeyCloakOIDCProviderList, items []*v3.KeyCloakOIDCProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
