// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeFleetWorkspaces implements FleetWorkspaceInterface
type fakeFleetWorkspaces struct {
	*gentype.FakeClientWithList[*v3.FleetWorkspace, *v3.FleetWorkspaceList]
	Fake *FakeManagementV3
}

func newFakeFleetWorkspaces(fake *FakeManagementV3) managementcattleiov3.FleetWorkspaceInterface {
	return &fakeFleetWorkspaces{
		gentype.NewFakeClientWithList[*v3.FleetWorkspace, *v3.FleetWorkspaceList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("fleetworkspaces"),
			v3.SchemeGroupVersion.WithKind("FleetWorkspace"),
			func() *v3.FleetWorkspace { return &v3.FleetWorkspace{} },
			func() *v3.FleetWorkspaceList { return &v3.FleetWorkspaceList{} },
			func(dst, src *v3.FleetWorkspaceList) { dst.ListMeta = src.ListMeta },
			func(list *v3.FleetWorkspaceList) []*v3.FleetWorkspace { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.FleetWorkspaceList, items []*v3.FleetWorkspace) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
