// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeGithubProviders implements GithubProviderInterface
type fakeGithubProviders struct {
	*gentype.FakeClientWithList[*v3.GithubProvider, *v3.GithubProviderList]
	Fake *FakeManagementV3
}

func newFakeGithubProviders(fake *FakeManagementV3) managementcattleiov3.GithubProviderInterface {
	return &fakeGithubProviders{
		gentype.NewFakeClientWithList[*v3.GithubProvider, *v3.GithubProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("githubproviders"),
			v3.SchemeGroupVersion.WithKind("GithubProvider"),
			func() *v3.GithubProvider { return &v3.GithubProvider{} },
			func() *v3.GithubProviderList { return &v3.GithubProviderList{} },
			func(dst, src *v3.GithubProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.GithubProviderList) []*v3.GithubProvider { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.GithubProviderList, items []*v3.GithubProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
