// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeAzureADProviders implements AzureADProviderInterface
type fakeAzureADProviders struct {
	*gentype.FakeClientWithList[*v3.AzureADProvider, *v3.AzureADProviderList]
	Fake *FakeManagementV3
}

func newFakeAzureADProviders(fake *FakeManagementV3) managementcattleiov3.AzureADProviderInterface {
	return &fakeAzureADProviders{
		gentype.NewFakeClientWithList[*v3.AzureADProvider, *v3.AzureADProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("azureadproviders"),
			v3.SchemeGroupVersion.WithKind("AzureADProvider"),
			func() *v3.AzureADProvider { return &v3.AzureADProvider{} },
			func() *v3.AzureADProviderList { return &v3.AzureADProviderList{} },
			func(dst, src *v3.AzureADProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.AzureADProviderList) []*v3.AzureADProvider { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.AzureADProviderList, items []*v3.AzureADProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
