// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeAuthProviders implements AuthProviderInterface
type fakeAuthProviders struct {
	*gentype.FakeClientWithList[*v3.AuthProvider, *v3.AuthProviderList]
	Fake *FakeManagementV3
}

func newFakeAuthProviders(fake *FakeManagementV3) managementcattleiov3.AuthProviderInterface {
	return &fakeAuthProviders{
		gentype.NewFakeClientWithList[*v3.AuthProvider, *v3.AuthProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("authproviders"),
			v3.SchemeGroupVersion.WithKind("AuthProvider"),
			func() *v3.AuthProvider { return &v3.AuthProvider{} },
			func() *v3.AuthProviderList { return &v3.AuthProviderList{} },
			func(dst, src *v3.AuthProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.AuthProviderList) []*v3.AuthProvider { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.AuthProviderList, items []*v3.AuthProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
