// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeRoleTemplates implements RoleTemplateInterface
type fakeRoleTemplates struct {
	*gentype.FakeClientWithList[*v3.RoleTemplate, *v3.RoleTemplateList]
	Fake *FakeManagementV3
}

func newFakeRoleTemplates(fake *FakeManagementV3) managementcattleiov3.RoleTemplateInterface {
	return &fakeRoleTemplates{
		gentype.NewFakeClientWithList[*v3.RoleTemplate, *v3.RoleTemplateList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("roletemplates"),
			v3.SchemeGroupVersion.WithKind("RoleTemplate"),
			func() *v3.RoleTemplate { return &v3.RoleTemplate{} },
			func() *v3.RoleTemplateList { return &v3.RoleTemplateList{} },
			func(dst, src *v3.RoleTemplateList) { dst.ListMeta = src.ListMeta },
			func(list *v3.RoleTemplateList) []*v3.RoleTemplate { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.RoleTemplateList, items []*v3.RoleTemplate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
