// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakePrincipals implements PrincipalInterface
type fakePrincipals struct {
	*gentype.FakeClientWithList[*v3.Principal, *v3.PrincipalList]
	Fake *FakeManagementV3
}

func newFakePrincipals(fake *FakeManagementV3) managementcattleiov3.PrincipalInterface {
	return &fakePrincipals{
		gentype.NewFakeClientWithList[*v3.Principal, *v3.PrincipalList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("principals"),
			v3.SchemeGroupVersion.WithKind("Principal"),
			func() *v3.Principal { return &v3.Principal{} },
			func() *v3.PrincipalList { return &v3.PrincipalList{} },
			func(dst, src *v3.PrincipalList) { dst.ListMeta = src.ListMeta },
			func(list *v3.PrincipalList) []*v3.Principal { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.PrincipalList, items []*v3.Principal) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
