// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeAPIServices implements APIServiceInterface
type fakeAPIServices struct {
	*gentype.FakeClientWithList[*v3.APIService, *v3.APIServiceList]
	Fake *FakeManagementV3
}

func newFakeAPIServices(fake *FakeManagementV3) managementcattleiov3.APIServiceInterface {
	return &fakeAPIServices{
		gentype.NewFakeClientWithList[*v3.APIService, *v3.APIServiceList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("apiservices"),
			v3.SchemeGroupVersion.WithKind("APIService"),
			func() *v3.APIService { return &v3.APIService{} },
			func() *v3.APIServiceList { return &v3.APIServiceList{} },
			func(dst, src *v3.APIServiceList) { dst.ListMeta = src.ListMeta },
			func(list *v3.APIServiceList) []*v3.APIService { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.APIServiceList, items []*v3.APIService) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
