// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeManagementV3 struct {
	*testing.Fake
}

func (c *FakeManagementV3) APIServices() v3.APIServiceInterface {
	return newFakeAPIServices(c)
}

func (c *FakeManagementV3) ActiveDirectoryProviders() v3.ActiveDirectoryProviderInterface {
	return newFakeActiveDirectoryProviders(c)
}

func (c *FakeManagementV3) AuthConfigs() v3.AuthConfigInterface {
	return newFakeAuthConfigs(c)
}

func (c *FakeManagementV3) AuthProviders() v3.AuthProviderInterface {
	return newFakeAuthProviders(c)
}

func (c *FakeManagementV3) AuthTokens() v3.AuthTokenInterface {
	return newFakeAuthTokens(c)
}

func (c *FakeManagementV3) AzureADProviders() v3.AzureADProviderInterface {
	return newFakeAzureADProviders(c)
}

func (c *FakeManagementV3) CloudCredentials(namespace string) v3.CloudCredentialInterface {
	return newFakeCloudCredentials(c, namespace)
}

func (c *FakeManagementV3) Clusters() v3.ClusterInterface {
	return newFakeClusters(c)
}

func (c *FakeManagementV3) ClusterProxyConfigs(namespace string) v3.ClusterProxyConfigInterface {
	return newFakeClusterProxyConfigs(c, namespace)
}

func (c *FakeManagementV3) ClusterRegistrationTokens(namespace string) v3.ClusterRegistrationTokenInterface {
	return newFakeClusterRegistrationTokens(c, namespace)
}

func (c *FakeManagementV3) ClusterRoleTemplateBindings(namespace string) v3.ClusterRoleTemplateBindingInterface {
	return newFakeClusterRoleTemplateBindings(c, namespace)
}

func (c *FakeManagementV3) CognitoProviders() v3.CognitoProviderInterface {
	return newFakeCognitoProviders(c)
}

func (c *FakeManagementV3) ComposeConfigs() v3.ComposeConfigInterface {
	return newFakeComposeConfigs(c)
}

func (c *FakeManagementV3) DynamicSchemas() v3.DynamicSchemaInterface {
	return newFakeDynamicSchemas(c)
}

func (c *FakeManagementV3) Features() v3.FeatureInterface {
	return newFakeFeatures(c)
}

func (c *FakeManagementV3) FleetWorkspaces() v3.FleetWorkspaceInterface {
	return newFakeFleetWorkspaces(c)
}

func (c *FakeManagementV3) FreeIpaProviders() v3.FreeIpaProviderInterface {
	return newFakeFreeIpaProviders(c)
}

func (c *FakeManagementV3) GenericOIDCProviders() v3.GenericOIDCProviderInterface {
	return newFakeGenericOIDCProviders(c)
}

func (c *FakeManagementV3) GithubAppConfigs() v3.GithubAppConfigInterface {
	return newFakeGithubAppConfigs(c)
}

func (c *FakeManagementV3) GithubAppProviders() v3.GithubAppProviderInterface {
	return newFakeGithubAppProviders(c)
}

func (c *FakeManagementV3) GithubConfigs() v3.GithubConfigInterface {
	return newFakeGithubConfigs(c)
}

func (c *FakeManagementV3) GithubProviders() v3.GithubProviderInterface {
	return newFakeGithubProviders(c)
}

func (c *FakeManagementV3) GlobalRoles() v3.GlobalRoleInterface {
	return newFakeGlobalRoles(c)
}

func (c *FakeManagementV3) GlobalRoleBindings() v3.GlobalRoleBindingInterface {
	return newFakeGlobalRoleBindings(c)
}

func (c *FakeManagementV3) GoogleOAuthProviders() v3.GoogleOAuthProviderInterface {
	return newFakeGoogleOAuthProviders(c)
}

func (c *FakeManagementV3) Groups() v3.GroupInterface {
	return newFakeGroups(c)
}

func (c *FakeManagementV3) GroupMembers() v3.GroupMemberInterface {
	return newFakeGroupMembers(c)
}

func (c *FakeManagementV3) KeyCloakOIDCProviders() v3.KeyCloakOIDCProviderInterface {
	return newFakeKeyCloakOIDCProviders(c)
}

func (c *FakeManagementV3) KontainerDrivers() v3.KontainerDriverInterface {
	return newFakeKontainerDrivers(c)
}

func (c *FakeManagementV3) LocalProviders() v3.LocalProviderInterface {
	return newFakeLocalProviders(c)
}

func (c *FakeManagementV3) ManagedCharts(namespace string) v3.ManagedChartInterface {
	return newFakeManagedCharts(c, namespace)
}

func (c *FakeManagementV3) Nodes(namespace string) v3.NodeInterface {
	return newFakeNodes(c, namespace)
}

func (c *FakeManagementV3) NodeDrivers() v3.NodeDriverInterface {
	return newFakeNodeDrivers(c)
}

func (c *FakeManagementV3) OIDCClients() v3.OIDCClientInterface {
	return newFakeOIDCClients(c)
}

func (c *FakeManagementV3) OIDCProviders() v3.OIDCProviderInterface {
	return newFakeOIDCProviders(c)
}

func (c *FakeManagementV3) OpenLdapProviders() v3.OpenLdapProviderInterface {
	return newFakeOpenLdapProviders(c)
}

func (c *FakeManagementV3) PodSecurityAdmissionConfigurationTemplates() v3.PodSecurityAdmissionConfigurationTemplateInterface {
	return newFakePodSecurityAdmissionConfigurationTemplates(c)
}

func (c *FakeManagementV3) Preferences(namespace string) v3.PreferenceInterface {
	return newFakePreferences(c, namespace)
}

func (c *FakeManagementV3) Principals() v3.PrincipalInterface {
	return newFakePrincipals(c)
}

func (c *FakeManagementV3) Projects(namespace string) v3.ProjectInterface {
	return newFakeProjects(c, namespace)
}

func (c *FakeManagementV3) ProjectNetworkPolicies(namespace string) v3.ProjectNetworkPolicyInterface {
	return newFakeProjectNetworkPolicies(c, namespace)
}

func (c *FakeManagementV3) ProjectRoleTemplateBindings(namespace string) v3.ProjectRoleTemplateBindingInterface {
	return newFakeProjectRoleTemplateBindings(c, namespace)
}

func (c *FakeManagementV3) ProxyEndpoints() v3.ProxyEndpointInterface {
	return newFakeProxyEndpoints(c)
}

func (c *FakeManagementV3) RancherUserNotifications() v3.RancherUserNotificationInterface {
	return newFakeRancherUserNotifications(c)
}

func (c *FakeManagementV3) RoleTemplates() v3.RoleTemplateInterface {
	return newFakeRoleTemplates(c)
}

func (c *FakeManagementV3) SamlProviders() v3.SamlProviderInterface {
	return newFakeSamlProviders(c)
}

func (c *FakeManagementV3) SamlTokens(namespace string) v3.SamlTokenInterface {
	return newFakeSamlTokens(c, namespace)
}

func (c *FakeManagementV3) Settings() v3.SettingInterface {
	return newFakeSettings(c)
}

func (c *FakeManagementV3) Tokens() v3.TokenInterface {
	return newFakeTokens(c)
}

func (c *FakeManagementV3) Users() v3.UserInterface {
	return newFakeUsers(c)
}

func (c *FakeManagementV3) UserAttributes() v3.UserAttributeInterface {
	return newFakeUserAttributes(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeManagementV3) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
