// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeManagedCharts implements ManagedChartInterface
type fakeManagedCharts struct {
	*gentype.FakeClientWithList[*v3.ManagedChart, *v3.ManagedChartList]
	Fake *FakeManagementV3
}

func newFakeManagedCharts(fake *FakeManagementV3, namespace string) managementcattleiov3.ManagedChartInterface {
	return &fakeManagedCharts{
		gentype.NewFakeClientWithList[*v3.ManagedChart, *v3.ManagedChartList](
			fake.Fake,
			namespace,
			v3.SchemeGroupVersion.WithResource("managedcharts"),
			v3.SchemeGroupVersion.WithKind("ManagedChart"),
			func() *v3.ManagedChart { return &v3.ManagedChart{} },
			func() *v3.ManagedChartList { return &v3.ManagedChartList{} },
			func(dst, src *v3.ManagedChartList) { dst.ListMeta = src.ListMeta },
			func(list *v3.ManagedChartList) []*v3.ManagedChart { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.ManagedChartList, items []*v3.ManagedChart) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
