// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeNodes implements NodeInterface
type fakeNodes struct {
	*gentype.FakeClientWithList[*v3.Node, *v3.NodeList]
	Fake *FakeManagementV3
}

func newFakeNodes(fake *FakeManagementV3, namespace string) managementcattleiov3.NodeInterface {
	return &fakeNodes{
		gentype.NewFakeClientWithList[*v3.Node, *v3.NodeList](
			fake.Fake,
			namespace,
			v3.SchemeGroupVersion.WithResource("nodes"),
			v3.SchemeGroupVersion.WithKind("Node"),
			func() *v3.Node { return &v3.Node{} },
			func() *v3.NodeList { return &v3.NodeList{} },
			func(dst, src *v3.NodeList) { dst.ListMeta = src.ListMeta },
			func(list *v3.NodeList) []*v3.Node { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.NodeList, items []*v3.Node) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
