// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeFreeIpaProviders implements FreeIpaProviderInterface
type fakeFreeIpaProviders struct {
	*gentype.FakeClientWithList[*v3.FreeIpaProvider, *v3.FreeIpaProviderList]
	Fake *FakeManagementV3
}

func newFakeFreeIpaProviders(fake *FakeManagementV3) managementcattleiov3.FreeIpaProviderInterface {
	return &fakeFreeIpaProviders{
		gentype.NewFakeClientWithList[*v3.FreeIpaProvider, *v3.FreeIpaProviderList](
			fake.Fake,
			"",
			v3.SchemeGroupVersion.WithResource("freeipaproviders"),
			v3.SchemeGroupVersion.WithKind("FreeIpaProvider"),
			func() *v3.FreeIpaProvider { return &v3.FreeIpaProvider{} },
			func() *v3.FreeIpaProviderList { return &v3.FreeIpaProviderList{} },
			func(dst, src *v3.FreeIpaProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v3.FreeIpaProviderList) []*v3.FreeIpaProvider { return gentype.ToPointerSlice(list.Items) },
			func(list *v3.FreeIpaProviderList, items []*v3.FreeIpaProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
