// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "github.com/rancher/rancher/pkg/apis/management.cattle.io/v3"
	managementcattleiov3 "github.com/rancher/rancher/pkg/client/versioned/typed/management.cattle.io/v3"
	gentype "k8s.io/client-go/gentype"
)

// fakeClusterRoleTemplateBindings implements ClusterRoleTemplateBindingInterface
type fakeClusterRoleTemplateBindings struct {
	*gentype.FakeClientWithList[*v3.ClusterRoleTemplateBinding, *v3.ClusterRoleTemplateBindingList]
	Fake *FakeManagementV3
}

func newFakeClusterRoleTemplateBindings(fake *FakeManagementV3, namespace string) managementcattleiov3.ClusterRoleTemplateBindingInterface {
	return &fakeClusterRoleTemplateBindings{
		gentype.NewFakeClientWithList[*v3.ClusterRoleTemplateBinding, *v3.ClusterRoleTemplateBindingList](
			fake.Fake,
			namespace,
			v3.SchemeGroupVersion.WithResource("clusterroletemplatebindings"),
			v3.SchemeGroupVersion.WithKind("ClusterRoleTemplateBinding"),
			func() *v3.ClusterRoleTemplateBinding { return &v3.ClusterRoleTemplateBinding{} },
			func() *v3.ClusterRoleTemplateBindingList { return &v3.ClusterRoleTemplateBindingList{} },
			func(dst, src *v3.ClusterRoleTemplateBindingList) { dst.ListMeta = src.ListMeta },
			func(list *v3.ClusterRoleTemplateBindingList) []*v3.ClusterRoleTemplateBinding {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v3.ClusterRoleTemplateBindingList, items []*v3.ClusterRoleTemplateBinding) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
